In [0]:
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

In [0]:
!ls

gdrive	sample_data

In [0]:
!ls "/content/gdrive/My Drive/data2"

w2003.csv     w2008.csv  w2014.csv  w.csv	ww2010.csv  ww2016.csv
w2004.csv     w2009.csv  w2015.csv  ww2005.csv	ww2011.csv  ww2017.csv
w2005.csv     w2010.csv  w2016.csv  ww2006.csv	ww2012.csv  ww2018.csv
w2005.gsheet  w2011.csv  w2017.csv  ww2007.csv	ww2013.csv  ww2019.csv
w2006.csv     w2012.csv  w2018.csv  ww2008.csv	ww2014.csv
w2007.csv     w2013.csv  w2019.csv  ww2009.csv	ww2015.csv

In [0]:
import pandas as pd
import numpy as np

In [0]:
ww2005 = pd.read_csv('/content/gdrive/My Drive/data2/w2005.csv', encoding='cp949')
ww2005.head(10)

    지점          일시  평균기온(°C)  ...  합계 소형증발량(mm)  9-9강수(mm)  안개 계속시간(hr)
0  108  2005-01-01      -4.9  ...           1.2        NaN          NaN
1  108  2005-01-02       0.4  ...           1.5        0.0          NaN
2  108  2005-01-03       2.9  ...           0.8        1.5          NaN
3  108  2005-01-04      -4.9  ...           1.5        NaN          NaN
4  108  2005-01-05      -3.8  ...           1.2        NaN          NaN
5  108  2005-01-06       0.1  ...           1.4        0.0          NaN
6  108  2005-01-07      -2.9  ...           1.2        NaN          NaN
7  108  2005-01-08      -5.0  ...           1.5        0.0          NaN
8  108  2005-01-09      -8.0  ...           1.4        NaN          NaN
9  108  2005-01-10      -5.7  ...           0.8        0.0          NaN

[10 rows x 59 columns]

저장된 파일이름은 w2003,w2004....이렇게 바꾸었고,

평균기온(°C)/일강수량(mm)/평균 풍속(m/s)/평균 상대습도(%)/평균 전운량(1/10)만골라온 파일이 ww2003

***cloud : 운량 -> 맑음(0-2), 구름조금(3-5), 구름많음(6-8), 흐림(9-10이상) ***

*** temp: -4  매우추움,4-8추움,8-11쌀쌀,11-16 선선,16-22 좋음 22-27더움 28-매우더움** 

**humid : ~30 건조 , ~41 쾌적 , ~52 약간습함, ~60불쾌 , 이상 매우불쾌**
**cloud : ~1 바람없음 ~3산들바람 ~4보통바람 ~5센바람 그이상 거센바람**

http://www.weather.go.kr/weather/climate/past_cal.jsp   (구름)

http://www.hellot.net/new_hellot/magazine/magazine_read.html?code=202&sub=&idx=11746&page=&list=      (습도)

https://m.blog.naver.com/PostView.nhn?blogId=tourinside&logNo=220530678119&proxyReferer=https%3A%2F%2Fwww.google.com%2F     (풍속)
https://m.blog.naver.com/majaejun/70141502293    (강수량)

In [0]:
ww2005 = ww2005[['일시','평균기온(°C)', '일강수량(mm)','평균 풍속(m/s)','평균 상대습도(%)','평균 전운량(1/10)','강수 계속시간(hr)','10분 최다 강수량(mm)','1시간 최다강수량(mm)','일강수량(mm)']]
ww2005

             일시  평균기온(°C)  일강수량(mm)  ...  10분 최다 강수량(mm)  1시간 최다강수량(mm)  일강수량(mm)
0    2005-01-01      -4.9       NaN  ...             NaN            NaN       NaN
1    2005-01-02       0.4       0.0  ...             NaN            NaN       0.0
2    2005-01-03       2.9       1.5  ...             NaN            NaN       1.5
3    2005-01-04      -4.9       NaN  ...             NaN            NaN       NaN
4    2005-01-05      -3.8       NaN  ...             NaN            NaN       NaN
..          ...       ...       ...  ...             ...            ...       ...
360  2005-12-27      -6.9       NaN  ...             NaN            NaN       NaN
361  2005-12-28      -5.0       NaN  ...             NaN            NaN       NaN
362  2005-12-29      -2.9       NaN  ...             NaN            NaN       NaN
363  2005-12-30       0.1       0.3  ...             NaN            NaN       0.3
364  2005-12-31       1.4       NaN  ...             NaN            NaN       NaN

[365 rows x 10 columns]

In [0]:
ww2005.describe()

         평균기온(°C)    일강수량(mm)  ...  1시간 최다강수량(mm)    일강수량(mm)
count  365.000000  134.000000  ...      88.000000  134.000000
mean    12.139452   10.137313  ...       6.046591   10.137313
std     11.009181   20.761770  ...      10.085245   20.761770
min    -10.200000    0.000000  ...       0.000000    0.000000
25%      2.100000    0.100000  ...       0.400000    0.100000
50%     14.100000    1.000000  ...       2.000000    1.000000
75%     22.200000   10.500000  ...       7.250000   10.500000
max     30.200000  115.000000  ...      53.500000  115.000000

[8 rows x 9 columns]

In [0]:
df2006 = pd.read_csv('/content/gdrive/My Drive/data2/w2006.csv', encoding='cp949')
ww2006 = df2006[['일시','평균기온(°C)', '일강수량(mm)','평균 풍속(m/s)','평균 상대습도(%)','평균 전운량(1/10)','강수 계속시간(hr)','10분 최다 강수량(mm)','1시간 최다강수량(mm)','일강수량(mm)']]
df2007 = pd.read_csv('/content/gdrive/My Drive/data2/w2007.csv', encoding='cp949')
ww2007 = df2007[['일시','평균기온(°C)', '일강수량(mm)','평균 풍속(m/s)','평균 상대습도(%)','평균 전운량(1/10)','강수 계속시간(hr)','10분 최다 강수량(mm)','1시간 최다강수량(mm)','일강수량(mm)']]
df2008 = pd.read_csv('/content/gdrive/My Drive/data2/w2008.csv', encoding='cp949')
ww2008 = df2008[['일시','평균기온(°C)', '일강수량(mm)','평균 풍속(m/s)','평균 상대습도(%)','평균 전운량(1/10)','강수 계속시간(hr)','10분 최다 강수량(mm)','1시간 최다강수량(mm)','일강수량(mm)']]
df2009 = pd.read_csv('/content/gdrive/My Drive/data2/w2009.csv', encoding='cp949')
ww2009 = df2009[['일시','평균기온(°C)', '일강수량(mm)','평균 풍속(m/s)','평균 상대습도(%)','평균 전운량(1/10)','강수 계속시간(hr)','10분 최다 강수량(mm)','1시간 최다강수량(mm)','일강수량(mm)']]
df2010 = pd.read_csv('/content/gdrive/My Drive/data2/w2010.csv', encoding='cp949')
ww2010 = df2010[['일시','평균기온(°C)', '일강수량(mm)','평균 풍속(m/s)','평균 상대습도(%)','평균 전운량(1/10)','강수 계속시간(hr)','10분 최다 강수량(mm)','1시간 최다강수량(mm)','일강수량(mm)']]
df2011 = pd.read_csv('/content/gdrive/My Drive/data2/w2011.csv', encoding='cp949')
ww2011 = df2011[['일시','평균기온(°C)', '일강수량(mm)','평균 풍속(m/s)','평균 상대습도(%)','평균 전운량(1/10)','강수 계속시간(hr)','10분 최다 강수량(mm)','1시간 최다강수량(mm)','일강수량(mm)']]
df2012 = pd.read_csv('/content/gdrive/My Drive/data2/w2012.csv', encoding='cp949')
ww2012 = df2012[['일시','평균기온(°C)', '일강수량(mm)','평균 풍속(m/s)','평균 상대습도(%)','평균 전운량(1/10)','강수 계속시간(hr)','10분 최다 강수량(mm)','1시간 최다강수량(mm)','일강수량(mm)']]
df2013 = pd.read_csv('/content/gdrive/My Drive/data2/w2013.csv', encoding='cp949')
ww2013 = df2013[['일시','평균기온(°C)', '일강수량(mm)','평균 풍속(m/s)','평균 상대습도(%)','평균 전운량(1/10)','강수 계속시간(hr)','10분 최다 강수량(mm)','1시간 최다강수량(mm)','일강수량(mm)']]
df2014 = pd.read_csv('/content/gdrive/My Drive/data2/w2014.csv', encoding='cp949')
ww2014 = df2014[['일시','평균기온(°C)', '일강수량(mm)','평균 풍속(m/s)','평균 상대습도(%)','평균 전운량(1/10)','강수 계속시간(hr)','10분 최다 강수량(mm)','1시간 최다강수량(mm)','일강수량(mm)']]
df2015 = pd.read_csv('/content/gdrive/My Drive/data2/w2015.csv', encoding='cp949')
ww2015 = df2015[['일시','평균기온(°C)', '일강수량(mm)','평균 풍속(m/s)','평균 상대습도(%)','평균 전운량(1/10)','강수 계속시간(hr)','10분 최다 강수량(mm)','1시간 최다강수량(mm)','일강수량(mm)']]
df2016 = pd.read_csv('/content/gdrive/My Drive/data2/w2016.csv', encoding='cp949')
ww2016 = df2016[['일시','평균기온(°C)', '일강수량(mm)','평균 풍속(m/s)','평균 상대습도(%)','평균 전운량(1/10)','강수 계속시간(hr)','10분 최다 강수량(mm)','1시간 최다강수량(mm)','일강수량(mm)']]
df2017= pd.read_csv('/content/gdrive/My Drive/data2/w2017.csv', encoding='cp949')
ww2017 = df2017[['일시','평균기온(°C)', '일강수량(mm)','평균 풍속(m/s)','평균 상대습도(%)','평균 전운량(1/10)','강수 계속시간(hr)','10분 최다 강수량(mm)','1시간 최다강수량(mm)','일강수량(mm)']]
df2018 = pd.read_csv('/content/gdrive/My Drive/data2/w2018.csv', encoding='cp949')
ww2018 = df2018[['일시','평균기온(°C)', '일강수량(mm)','평균 풍속(m/s)','평균 상대습도(%)','평균 전운량(1/10)','강수 계속시간(hr)','10분 최다 강수량(mm)','1시간 최다강수량(mm)','일강수량(mm)']]
df2019 = pd.read_csv('/content/gdrive/My Drive/data2/w2019.csv', encoding='cp949')
ww2019 = df2019[['일시','평균기온(°C)', '일강수량(mm)','평균 풍속(m/s)','평균 상대습도(%)','평균 전운량(1/10)','강수 계속시간(hr)','10분 최다 강수량(mm)','1시간 최다강수량(mm)','일강수량(mm)']]

2005년먼저

cloud 처리 ( 맑음,구름조금.구름많음,흐림)

In [0]:
#ww2003.rename(columns={'일시': 'when', '평균기온(°C)': 'temp','일강수량(mm)': 'rain','평균 풍속(m/s)': 'wind',v,'평균 상대습도(%)': ' humid','평균 전운량(1/10)': 'cloud'}, inplace=True)
ww2005.columns.values[0] = "when"
ww2005.columns.values[1] = "temp"
ww2005.columns.values[2] = "rain"
ww2005.columns.values[3] = "wind"
ww2005.columns.values[4] = "humid"
ww2005.columns.values[5] = "cloud"
ww2005 = ww2005.fillna(0)
#NAN값 0처리
ww2005.head(10)

         when  temp  rain  ...  10분 최다 강수량(mm)  1시간 최다강수량(mm)  일강수량(mm)
0  2005-01-01  -4.9   0.0  ...             0.0            0.0       0.0
1  2005-01-02   0.4   0.0  ...             0.0            0.0       0.0
2  2005-01-03   2.9   1.5  ...             0.0            0.0       1.5
3  2005-01-04  -4.9   0.0  ...             0.0            0.0       0.0
4  2005-01-05  -3.8   0.0  ...             0.0            0.0       0.0
5  2005-01-06   0.1   0.0  ...             0.0            0.0       0.0
6  2005-01-07  -2.9   0.0  ...             0.0            0.0       0.0
7  2005-01-08  -5.0   0.0  ...             0.0            0.0       0.0
8  2005-01-09  -8.0   0.0  ...             0.0            0.0       0.0
9  2005-01-10  -5.7   0.0  ...             0.0            0.0       0.0

[10 rows x 10 columns]

In [0]:
ww2005['cloud2']=0
ww2005.loc[ww2005['cloud']<3,'cloud2']='구름조금'
ww2005.loc[(ww2005['cloud']>=3)&(ww2005['cloud']< 6),'cloud2']='맑음'
ww2005.loc[(ww2005['cloud']>=6)&(ww2005['cloud']<=9),'cloud2']='구름많음'
ww2005.loc[ww2005['cloud']>=9,'cloud2']='흐림'

ww2005.head(10)

         when  temp  rain  wind  ...  10분 최다 강수량(mm)  1시간 최다강수량(mm)  일강수량(mm)  cloud2
0  2005-01-01  -4.9   0.0   2.1  ...             0.0            0.0       0.0    구름조금
1  2005-01-02   0.4   0.0   2.8  ...             0.0            0.0       0.0      맑음
2  2005-01-03   2.9   1.5   3.6  ...             0.0            0.0       1.5    구름많음
3  2005-01-04  -4.9   0.0   3.2  ...             0.0            0.0       0.0    구름조금
4  2005-01-05  -3.8   0.0   1.6  ...             0.0            0.0       0.0      맑음
5  2005-01-06   0.1   0.0   2.0  ...             0.0            0.0       0.0    구름많음
6  2005-01-07  -2.9   0.0   3.6  ...             0.0            0.0       0.0    구름조금
7  2005-01-08  -5.0   0.0   2.6  ...             0.0            0.0       0.0    구름조금
8  2005-01-09  -8.0   0.0   2.9  ...             0.0            0.0       0.0    구름조금
9  2005-01-10  -5.7   0.0   2.1  ...             0.0            0.0       0.0      맑음

[10 rows x 11 columns]

In [0]:
ww2005['cloud_1234_4isMax']=0
ww2005.loc[ww2005['cloud']<3,'cloud_1234_4isMax']='1'
ww2005.loc[(ww2005['cloud']>=3)&(ww2005['cloud']< 6),'cloud_1234_4isMax']='2'
ww2005.loc[(ww2005['cloud']>=6)&(ww2005['cloud']<=9),'cloud_1234_4isMax']='3'
ww2005.loc[ww2005['cloud']>=9,'cloud_1234_4isMax']='4'

ww2005.head(10)

         when  temp  rain  ...  일강수량(mm)  cloud2  cloud_1234_4isMax
0  2005-01-01  -4.9   0.0  ...       0.0    구름조금                  1
1  2005-01-02   0.4   0.0  ...       0.0      맑음                  2
2  2005-01-03   2.9   1.5  ...       1.5    구름많음                  3
3  2005-01-04  -4.9   0.0  ...       0.0    구름조금                  1
4  2005-01-05  -3.8   0.0  ...       0.0      맑음                  2
5  2005-01-06   0.1   0.0  ...       0.0    구름많음                  3
6  2005-01-07  -2.9   0.0  ...       0.0    구름조금                  1
7  2005-01-08  -5.0   0.0  ...       0.0    구름조금                  1
8  2005-01-09  -8.0   0.0  ...       0.0    구름조금                  1
9  2005-01-10  -5.7   0.0  ...       0.0      맑음                  2

[10 rows x 12 columns]

In [0]:
ww2005['cloud2'].value_counts()
#총 365개값 확인

구름조금    145
맑음       91
구름많음     90
흐림       39
Name: cloud2, dtype: int64

In [0]:
ww2005 = pd.get_dummies(data=ww2005, columns=['cloud2'], prefix='cloud')
ww2005

           when  temp  rain  wind  ...  cloud_구름많음  cloud_구름조금  cloud_맑음  cloud_흐림
0    2005-01-01  -4.9   0.0   2.1  ...           0           1         0         0
1    2005-01-02   0.4   0.0   2.8  ...           0           0         1         0
2    2005-01-03   2.9   1.5   3.6  ...           1           0         0         0
3    2005-01-04  -4.9   0.0   3.2  ...           0           1         0         0
4    2005-01-05  -3.8   0.0   1.6  ...           0           0         1         0
..          ...   ...   ...   ...  ...         ...         ...       ...       ...
360  2005-12-27  -6.9   0.0   2.5  ...           0           1         0         0
361  2005-12-28  -5.0   0.0   1.7  ...           0           1         0         0
362  2005-12-29  -2.9   0.0   1.5  ...           0           1         0         0
363  2005-12-30   0.1   0.3   1.8  ...           0           0         1         0
364  2005-12-31   1.4   0.0   2.5  ...           0           0         1         0

[365 rows x 15 columns]

In [0]:
ww2005[ww2005.isnull().any(axis=1)].head(5)
#혹시 누락된 데이터가 있는지 다시한번 출력해봄, 없는것같음

Empty DataFrame
Columns: [when, temp, rain, wind, humid, cloud, 강수 계속시간(hr), 10분 최다 강수량(mm), 1시간 최다강수량(mm), 일강수량(mm), cloud_1234_4isMax, cloud_구름많음, cloud_구름조금, cloud_맑음, cloud_흐림]
Index: []

temp 처리

In [0]:
ww2005['temp2']=0
ww2005.loc[ww2005['temp'] < 4,'temp2']='매우추움'
ww2005.loc[(ww2005['temp']>=4)&(ww2005['temp']<8),'temp2']='추움'
ww2005.loc[(ww2005['temp']>=8)&(ww2005['temp']<11),'temp2']='쌀쌀'
ww2005.loc[(ww2005['temp']>=11)&(ww2005['temp']<16),'temp2']='선선'
ww2005.loc[(ww2005['temp']>=16)&(ww2005['temp']<22),'temp2']='좋음'
ww2005.loc[(ww2005['temp']>=22)&(ww2005['temp']<27),'temp2']='더움'
ww2005.loc[ww2005['temp'] >=27,'temp2']='매우더움'

ww2005.head(10)

         when  temp  rain  wind  ...  cloud_구름조금  cloud_맑음  cloud_흐림  temp2
0  2005-01-01  -4.9   0.0   2.1  ...           1         0         0   매우추움
1  2005-01-02   0.4   0.0   2.8  ...           0         1         0   매우추움
2  2005-01-03   2.9   1.5   3.6  ...           0         0         0   매우추움
3  2005-01-04  -4.9   0.0   3.2  ...           1         0         0   매우추움
4  2005-01-05  -3.8   0.0   1.6  ...           0         1         0   매우추움
5  2005-01-06   0.1   0.0   2.0  ...           0         0         0   매우추움
6  2005-01-07  -2.9   0.0   3.6  ...           1         0         0   매우추움
7  2005-01-08  -5.0   0.0   2.6  ...           1         0         0   매우추움
8  2005-01-09  -8.0   0.0   2.9  ...           1         0         0   매우추움
9  2005-01-10  -5.7   0.0   2.1  ...           0         1         0   매우추움

[10 rows x 16 columns]

In [0]:
ww2005['temp1to7_7isMax']=0
ww2005.loc[ww2005['temp'] < 4,'temp1to7_7isMax']=1
ww2005.loc[(ww2005['temp']>=4)&(ww2005['temp']<8),'temp1to7_7isMax']=2
ww2005.loc[(ww2005['temp']>=8)&(ww2005['temp']<11),'temp1to7_7isMax']=3
ww2005.loc[(ww2005['temp']>=11)&(ww2005['temp']<16),'temp1to7_7isMax']=4
ww2005.loc[(ww2005['temp']>=16)&(ww2005['temp']<22),'temp1to7_7isMax']=5
ww2005.loc[(ww2005['temp']>=22)&(ww2005['temp']<27),'temp1to7_7isMax']=6
ww2005.loc[ww2005['temp'] >=27,'temp1to7_7isMax']=7

ww2005.head(10)

         when  temp  rain  wind  ...  cloud_맑음  cloud_흐림  temp2  temp1to7_7isMax
0  2005-01-01  -4.9   0.0   2.1  ...         0         0   매우추움                1
1  2005-01-02   0.4   0.0   2.8  ...         1         0   매우추움                1
2  2005-01-03   2.9   1.5   3.6  ...         0         0   매우추움                1
3  2005-01-04  -4.9   0.0   3.2  ...         0         0   매우추움                1
4  2005-01-05  -3.8   0.0   1.6  ...         1         0   매우추움                1
5  2005-01-06   0.1   0.0   2.0  ...         0         0   매우추움                1
6  2005-01-07  -2.9   0.0   3.6  ...         0         0   매우추움                1
7  2005-01-08  -5.0   0.0   2.6  ...         0         0   매우추움                1
8  2005-01-09  -8.0   0.0   2.9  ...         0         0   매우추움                1
9  2005-01-10  -5.7   0.0   2.1  ...         1         0   매우추움                1

[10 rows x 17 columns]

In [0]:
ww2005 = pd.get_dummies(data=ww2005, columns=['temp2'], prefix='temp')
ww2005

           when  temp  rain  wind  ...  temp_선선  temp_쌀쌀  temp_좋음  temp_추움
0    2005-01-01  -4.9   0.0   2.1  ...        0        0        0        0
1    2005-01-02   0.4   0.0   2.8  ...        0        0        0        0
2    2005-01-03   2.9   1.5   3.6  ...        0        0        0        0
3    2005-01-04  -4.9   0.0   3.2  ...        0        0        0        0
4    2005-01-05  -3.8   0.0   1.6  ...        0        0        0        0
..          ...   ...   ...   ...  ...      ...      ...      ...      ...
360  2005-12-27  -6.9   0.0   2.5  ...        0        0        0        0
361  2005-12-28  -5.0   0.0   1.7  ...        0        0        0        0
362  2005-12-29  -2.9   0.0   1.5  ...        0        0        0        0
363  2005-12-30   0.1   0.3   1.8  ...        0        0        0        0
364  2005-12-31   1.4   0.0   2.5  ...        0        0        0        0

[365 rows x 23 columns]

습도

In [0]:
ww2005['humid2']=0
ww2005.loc[ww2005['humid'] < 30,'humid2']='건조'
ww2005.loc[(ww2005['humid']>=30)&(ww2005['humid']<41),'humid2']='쾌적'
ww2005.loc[(ww2005['humid']>=41)&(ww2005['humid']<52),'humid2']='보통'
ww2005.loc[(ww2005['humid']>=52)&(ww2005['humid']<60),'humid2']='불쾌'
ww2005.loc[ww2005['humid'] >=60,'humid2']='매우불쾌'

ww2005.head(10)

         when  temp  rain  wind  ...  temp_쌀쌀  temp_좋음  temp_추움  humid2
0  2005-01-01  -4.9   0.0   2.1  ...        0        0        0      보통
1  2005-01-02   0.4   0.0   2.8  ...        0        0        0      불쾌
2  2005-01-03   2.9   1.5   3.6  ...        0        0        0    매우불쾌
3  2005-01-04  -4.9   0.0   3.2  ...        0        0        0      쾌적
4  2005-01-05  -3.8   0.0   1.6  ...        0        0        0      보통
5  2005-01-06   0.1   0.0   2.0  ...        0        0        0      불쾌
6  2005-01-07  -2.9   0.0   3.6  ...        0        0        0      불쾌
7  2005-01-08  -5.0   0.0   2.6  ...        0        0        0      보통
8  2005-01-09  -8.0   0.0   2.9  ...        0        0        0      보통
9  2005-01-10  -5.7   0.0   2.1  ...        0        0        0      불쾌

[10 rows x 24 columns]

In [0]:
ww2005['humid1to5_5isMax']=0
ww2005.loc[ww2005['humid'] < 30,'humid1to5_5isMax']=1
ww2005.loc[(ww2005['humid']>=30)&(ww2005['humid']<41),'humid1to5_5isMax']=2
ww2005.loc[(ww2005['humid']>=41)&(ww2005['humid']<52),'humid1to5_5isMax']=3
ww2005.loc[(ww2005['humid']>=52)&(ww2005['humid']<60),'humid1to5_5isMax']=4
ww2005.loc[ww2005['humid'] >=60,'humid1to5_5isMax']=5

ww2005.head(10)

         when  temp  rain  wind  ...  temp_좋음  temp_추움  humid2  humid1to5_5isMax
0  2005-01-01  -4.9   0.0   2.1  ...        0        0      보통                 3
1  2005-01-02   0.4   0.0   2.8  ...        0        0      불쾌                 4
2  2005-01-03   2.9   1.5   3.6  ...        0        0    매우불쾌                 5
3  2005-01-04  -4.9   0.0   3.2  ...        0        0      쾌적                 2
4  2005-01-05  -3.8   0.0   1.6  ...        0        0      보통                 3
5  2005-01-06   0.1   0.0   2.0  ...        0        0      불쾌                 4
6  2005-01-07  -2.9   0.0   3.6  ...        0        0      불쾌                 4
7  2005-01-08  -5.0   0.0   2.6  ...        0        0      보통                 3
8  2005-01-09  -8.0   0.0   2.9  ...        0        0      보통                 3
9  2005-01-10  -5.7   0.0   2.1  ...        0        0      불쾌                 4

[10 rows x 25 columns]

In [0]:
ww2005 = pd.get_dummies(data=ww2005, columns=['humid2'], prefix='체감습도')
ww2005

           when  temp  rain  wind  ...  체감습도_매우불쾌  체감습도_보통  체감습도_불쾌  체감습도_쾌적
0    2005-01-01  -4.9   0.0   2.1  ...          0        1        0        0
1    2005-01-02   0.4   0.0   2.8  ...          0        0        1        0
2    2005-01-03   2.9   1.5   3.6  ...          1        0        0        0
3    2005-01-04  -4.9   0.0   3.2  ...          0        0        0        1
4    2005-01-05  -3.8   0.0   1.6  ...          0        1        0        0
..          ...   ...   ...   ...  ...        ...      ...      ...      ...
360  2005-12-27  -6.9   0.0   2.5  ...          0        1        0        0
361  2005-12-28  -5.0   0.0   1.7  ...          0        0        0        1
362  2005-12-29  -2.9   0.0   1.5  ...          0        1        0        0
363  2005-12-30   0.1   0.3   1.8  ...          1        0        0        0
364  2005-12-31   1.4   0.0   2.5  ...          1        0        0        0

[365 rows x 29 columns]

풍속

In [0]:
ww2005['wind2']=0
ww2005.loc[ww2005['wind'] < 1,'wind2']='바람없음'
ww2005.loc[(ww2005['wind']>=1)&(ww2005['wind']<3),'wind2']='산들바람'
ww2005.loc[(ww2005['wind']>=3)&(ww2005['wind']<4),'wind2']='보통바람'
ww2005.loc[(ww2005['wind']>=4)&(ww2005['wind']<5),'wind2']='센바람'
ww2005.loc[ww2005['wind'] >=4,'wind2']='거센바람'

ww2005.head(10)

         when  temp  rain  wind  ...  체감습도_보통  체감습도_불쾌  체감습도_쾌적  wind2
0  2005-01-01  -4.9   0.0   2.1  ...        1        0        0   산들바람
1  2005-01-02   0.4   0.0   2.8  ...        0        1        0   산들바람
2  2005-01-03   2.9   1.5   3.6  ...        0        0        0   보통바람
3  2005-01-04  -4.9   0.0   3.2  ...        0        0        1   보통바람
4  2005-01-05  -3.8   0.0   1.6  ...        1        0        0   산들바람
5  2005-01-06   0.1   0.0   2.0  ...        0        1        0   산들바람
6  2005-01-07  -2.9   0.0   3.6  ...        0        1        0   보통바람
7  2005-01-08  -5.0   0.0   2.6  ...        1        0        0   산들바람
8  2005-01-09  -8.0   0.0   2.9  ...        1        0        0   산들바람
9  2005-01-10  -5.7   0.0   2.1  ...        0        1        0   산들바람

[10 rows x 30 columns]

In [0]:
ww2005['wind1to5_5isStrong']=0
ww2005.loc[ww2005['wind'] < 1,'wind1to5_5isStrong']=0
ww2005.loc[(ww2005['wind']>=1)&(ww2005['wind']<3),'wind1to5_5isStrong']=1
ww2005.loc[(ww2005['wind']>=3)&(ww2005['wind']<4),'wind1to5_5isStrong']=2
ww2005.loc[(ww2005['wind']>=4)&(ww2005['wind']<5),'wind1to5_5isStrong']=3
ww2005.loc[ww2005['wind'] >=4,'wind1to5_5isStrong']=4

ww2005.head(10)

         when  temp  rain  wind  ...  체감습도_불쾌  체감습도_쾌적  wind2  wind1to5_5isStrong
0  2005-01-01  -4.9   0.0   2.1  ...        0        0   산들바람                   1
1  2005-01-02   0.4   0.0   2.8  ...        1        0   산들바람                   1
2  2005-01-03   2.9   1.5   3.6  ...        0        0   보통바람                   2
3  2005-01-04  -4.9   0.0   3.2  ...        0        1   보통바람                   2
4  2005-01-05  -3.8   0.0   1.6  ...        0        0   산들바람                   1
5  2005-01-06   0.1   0.0   2.0  ...        1        0   산들바람                   1
6  2005-01-07  -2.9   0.0   3.6  ...        1        0   보통바람                   2
7  2005-01-08  -5.0   0.0   2.6  ...        0        0   산들바람                   1
8  2005-01-09  -8.0   0.0   2.9  ...        0        0   산들바람                   1
9  2005-01-10  -5.7   0.0   2.1  ...        1        0   산들바람                   1

[10 rows x 31 columns]

In [0]:
ww2005 = pd.get_dummies(data=ww2005, columns=['wind2'], prefix='바람')
ww2005

           when  temp  rain  wind  ...  바람_거센바람  바람_바람없음  바람_보통바람  바람_산들바람
0    2005-01-01  -4.9   0.0   2.1  ...        0        0        0        1
1    2005-01-02   0.4   0.0   2.8  ...        0        0        0        1
2    2005-01-03   2.9   1.5   3.6  ...        0        0        1        0
3    2005-01-04  -4.9   0.0   3.2  ...        0        0        1        0
4    2005-01-05  -3.8   0.0   1.6  ...        0        0        0        1
..          ...   ...   ...   ...  ...      ...      ...      ...      ...
360  2005-12-27  -6.9   0.0   2.5  ...        0        0        0        1
361  2005-12-28  -5.0   0.0   1.7  ...        0        0        0        1
362  2005-12-29  -2.9   0.0   1.5  ...        0        0        0        1
363  2005-12-30   0.1   0.3   1.8  ...        0        0        0        1
364  2005-12-31   1.4   0.0   2.5  ...        0        0        0        1

[365 rows x 34 columns]

In [0]:
ww2006.columns.values[0] = "when"
ww2006.columns.values[1] = "temp"
ww2006.columns.values[2] = "rain"
ww2006.columns.values[3] = "wind"
ww2006.columns.values[4] = "humid"
ww2006.columns.values[5] = "cloud"
ww2006 = ww2006.fillna(0)
#NAN값 0처리
ww2006['cloud2']=0
ww2006.loc[ww2006['cloud']<3,'cloud2']='맑음'
ww2006.loc[(ww2006['cloud']>=3)&(ww2006['cloud']< 6),'cloud2']='구름조금'
ww2006.loc[(ww2006['cloud']>=6)&(ww2006['cloud']<=9),'cloud2']='구름많음'
ww2006.loc[ww2006['cloud']>=9,'cloud2']='흐림'
ww2006['cloud2'].value_counts()
#총 365개값 확인
ww2006 = pd.get_dummies(data=ww2006, columns=['cloud2'], prefix='cloud')
ww2006[ww2006.isnull().any(axis=1)].head(5)
#혹시 누락된 데이터가 있는지 다시한번 출력해봄, 없는것같음
ww2006['temp2']=0
ww2006.loc[ww2006['temp'] < 4,'temp2']='매우추움'
ww2006.loc[(ww2006['temp']>=4)&(ww2006['temp']<8),'temp2']='추움'
ww2006.loc[(ww2006['temp']>=8)&(ww2006['temp']<11),'temp2']='쌀쌀'
ww2006.loc[(ww2006['temp']>=11)&(ww2006['temp']<16),'temp2']='선선'
ww2006.loc[(ww2006['temp']>=16)&(ww2006['temp']<22),'temp2']='좋음'
ww2006.loc[(ww2006['temp']>=22)&(ww2006['temp']<27),'temp2']='더움'
ww2006.loc[ww2006['temp'] >=27,'temp2']='매우더움'
ww2006 = pd.get_dummies(data=ww2006, columns=['temp2'], prefix='temp')
ww2006['humid2']=0
ww2006.loc[ww2006['humid'] < 30,'humid2']='건조'
ww2006.loc[(ww2006['humid']>=30)&(ww2006['humid']<41),'humid2']='쾌적'
ww2006.loc[(ww2006['humid']>=41)&(ww2006['humid']<52),'humid2']='보통'
ww2006.loc[(ww2006['humid']>=52)&(ww2006['humid']<60),'humid2']='불쾌'
ww2006.loc[ww2006['humid'] >=60,'humid2']='매우불쾌'
ww2006 = pd.get_dummies(data=ww2006, columns=['humid2'], prefix='체감습도')
ww2006['wind2']=0
ww2006.loc[ww2006['wind'] < 1,'wind2']='바람없음'
ww2006.loc[(ww2006['wind']>=1)&(ww2006['wind']<3),'wind2']='산들바람'
ww2006.loc[(ww2006['wind']>=3)&(ww2006['wind']<4),'wind2']='보통바람'
ww2006.loc[(ww2006['wind']>=4)&(ww2006['wind']<5),'wind2']='센바람'
ww2006.loc[ww2006['wind'] >=4,'wind2']='거센바람'
ww2006 = pd.get_dummies(data=ww2006, columns=['wind2'], prefix='바람')
ww2006.head(10)

         when  temp  rain  wind  ...  체감습도_쾌적  바람_거센바람  바람_보통바람  바람_산들바람
0  2006-01-01   1.4   0.0   1.6  ...        0        0        0        1
1  2006-01-02   0.2   0.0   2.8  ...        0        0        0        1
2  2006-01-03  -2.4   0.0   2.9  ...        1        0        0        1
3  2006-01-04  -6.2   0.0   2.8  ...        0        0        0        1
4  2006-01-05  -7.1   0.0   2.5  ...        1        0        0        1
5  2006-01-06  -7.5   0.0   2.8  ...        0        0        0        1
6  2006-01-07  -6.2   0.0   2.3  ...        1        0        0        1
7  2006-01-08  -4.2   0.0   1.4  ...        0        0        0        1
8  2006-01-09  -1.6   0.3   1.7  ...        0        0        0        1
9  2006-01-10  -0.3   0.0   2.0  ...        0        0        0        1

[10 rows x 29 columns]

In [0]:
ww2007.columns.values[0] = "when"
ww2007.columns.values[1] = "temp"
ww2007.columns.values[2] = "rain"
ww2007.columns.values[3] = "wind"
ww2007.columns.values[4] = "humid"
ww2007.columns.values[5] = "cloud"
ww2007 = ww2007.fillna(0)
#NAN값 0처리
ww2007['cloud2']=0
ww2007.loc[ww2007['cloud']<3,'cloud2']='맑음'
ww2007.loc[(ww2007['cloud']>=3)&(ww2007['cloud']< 6),'cloud2']='구름조금'
ww2007.loc[(ww2007['cloud']>=6)&(ww2007['cloud']<=9),'cloud2']='구름많음'
ww2007.loc[ww2007['cloud']>=9,'cloud2']='흐림'
ww2007['cloud2'].value_counts()
#총 365개값 확인
ww2007 = pd.get_dummies(data=ww2007, columns=['cloud2'], prefix='cloud')
ww2007[ww2007.isnull().any(axis=1)].head(5)
#혹시 누락된 데이터가 있는지 다시한번 출력해봄, 없는것같음
ww2007['temp2']=0
ww2007.loc[ww2007['temp'] < 4,'temp2']='매우추움'
ww2007.loc[(ww2007['temp']>=4)&(ww2007['temp']<8),'temp2']='추움'
ww2007.loc[(ww2007['temp']>=8)&(ww2007['temp']<11),'temp2']='쌀쌀'
ww2007.loc[(ww2007['temp']>=11)&(ww2007['temp']<16),'temp2']='선선'
ww2007.loc[(ww2007['temp']>=16)&(ww2007['temp']<22),'temp2']='좋음'
ww2007.loc[(ww2007['temp']>=22)&(ww2007['temp']<27),'temp2']='더움'
ww2007.loc[ww2007['temp'] >=27,'temp2']='매우더움'
ww2007 = pd.get_dummies(data=ww2007, columns=['temp2'], prefix='temp')
ww2007['humid2']=0
ww2007.loc[ww2007['humid'] < 30,'humid2']='건조'
ww2007.loc[(ww2007['humid']>=30)&(ww2007['humid']<41),'humid2']='쾌적'
ww2007.loc[(ww2007['humid']>=41)&(ww2007['humid']<52),'humid2']='보통'
ww2007.loc[(ww2007['humid']>=52)&(ww2007['humid']<60),'humid2']='불쾌'
ww2007.loc[ww2007['humid'] >=60,'humid2']='매우불쾌'
ww2007 = pd.get_dummies(data=ww2007, columns=['humid2'], prefix='체감습도')
ww2007['wind2']=0
ww2007.loc[ww2007['wind'] < 1,'wind2']='바람없음'
ww2007.loc[(ww2007['wind']>=1)&(ww2007['wind']<3),'wind2']='산들바람'
ww2007.loc[(ww2007['wind']>=3)&(ww2007['wind']<4),'wind2']='보통바람'
ww2007.loc[(ww2007['wind']>=4)&(ww2007['wind']<5),'wind2']='센바람'
ww2007.loc[ww2007['wind'] >=4,'wind2']='거센바람'
ww2007 = pd.get_dummies(data=ww2007, columns=['wind2'], prefix='바람')

In [0]:
ww2008.columns.values[0] = "when"
ww2008.columns.values[1] = "temp"
ww2008.columns.values[2] = "rain"
ww2008.columns.values[3] = "wind"
ww2008.columns.values[4] = "humid"
ww2008.columns.values[5] = "cloud"
ww2008 = ww2008.fillna(0)
#NAN값 0처리
ww2008['cloud2']=0
ww2008.loc[ww2008['cloud']<3,'cloud2']='맑음'
ww2008.loc[(ww2008['cloud']>=3)&(ww2008['cloud']< 6),'cloud2']='구름조금'
ww2008.loc[(ww2008['cloud']>=6)&(ww2008['cloud']<=9),'cloud2']='구름많음'
ww2008.loc[ww2008['cloud']>=9,'cloud2']='흐림'
ww2008['cloud2'].value_counts()
#총 365개값 확인
ww2008 = pd.get_dummies(data=ww2008, columns=['cloud2'], prefix='cloud')
ww2008[ww2008.isnull().any(axis=1)].head(5)
#혹시 누락된 데이터가 있는지 다시한번 출력해봄, 없는것같음
ww2008['temp2']=0
ww2008.loc[ww2008['temp'] < 4,'temp2']='매우추움'
ww2008.loc[(ww2008['temp']>=4)&(ww2008['temp']<8),'temp2']='추움'
ww2008.loc[(ww2008['temp']>=8)&(ww2008['temp']<11),'temp2']='쌀쌀'
ww2008.loc[(ww2008['temp']>=11)&(ww2008['temp']<16),'temp2']='선선'
ww2008.loc[(ww2008['temp']>=16)&(ww2008['temp']<22),'temp2']='좋음'
ww2008.loc[(ww2008['temp']>=22)&(ww2008['temp']<27),'temp2']='더움'
ww2008.loc[ww2008['temp'] >=27,'temp2']='매우더움'
ww2008 = pd.get_dummies(data=ww2008, columns=['temp2'], prefix='temp')
ww2008['humid2']=0
ww2008.loc[ww2008['humid'] < 30,'humid2']='건조'
ww2008.loc[(ww2008['humid']>=30)&(ww2008['humid']<41),'humid2']='쾌적'
ww2008.loc[(ww2008['humid']>=41)&(ww2008['humid']<52),'humid2']='보통'
ww2008.loc[(ww2008['humid']>=52)&(ww2008['humid']<60),'humid2']='불쾌'
ww2008.loc[ww2008['humid'] >=60,'humid2']='매우불쾌'
ww2008 = pd.get_dummies(data=ww2008, columns=['humid2'], prefix='체감습도')
ww2008['wind2']=0
ww2008.loc[ww2008['wind'] < 1,'wind2']='바람없음'
ww2008.loc[(ww2008['wind']>=1)&(ww2008['wind']<3),'wind2']='산들바람'
ww2008.loc[(ww2008['wind']>=3)&(ww2008['wind']<4),'wind2']='보통바람'
ww2008.loc[(ww2008['wind']>=4)&(ww2008['wind']<5),'wind2']='센바람'
ww2008.loc[ww2008['wind'] >=4,'wind2']='거센바람'
ww2008 = pd.get_dummies(data=ww2008, columns=['wind2'], prefix='바람')

In [0]:
ww2009.columns.values[0] = "when"
ww2009.columns.values[1] = "temp"
ww2009.columns.values[2] = "rain"
ww2009.columns.values[3] = "wind"
ww2009.columns.values[4] = "humid"
ww2009.columns.values[5] = "cloud"
ww2009 = ww2009.fillna(0)
#NAN값 0처리
ww2009['cloud2']=0
ww2009.loc[ww2009['cloud']<3,'cloud2']='맑음'
ww2009.loc[(ww2009['cloud']>=3)&(ww2009['cloud']< 6),'cloud2']='구름조금'
ww2009.loc[(ww2009['cloud']>=6)&(ww2009['cloud']<=9),'cloud2']='구름많음'
ww2009.loc[ww2009['cloud']>=9,'cloud2']='흐림'
ww2009['cloud2'].value_counts()
#총 365개값 확인
ww2009 = pd.get_dummies(data=ww2009, columns=['cloud2'], prefix='cloud')
ww2009[ww2009.isnull().any(axis=1)].head(5)
#혹시 누락된 데이터가 있는지 다시한번 출력해봄, 없는것같음
ww2009['temp2']=0
ww2009.loc[ww2009['temp'] < 4,'temp2']='매우추움'
ww2009.loc[(ww2009['temp']>=4)&(ww2009['temp']<8),'temp2']='추움'
ww2009.loc[(ww2009['temp']>=8)&(ww2009['temp']<11),'temp2']='쌀쌀'
ww2009.loc[(ww2009['temp']>=11)&(ww2009['temp']<16),'temp2']='선선'
ww2009.loc[(ww2009['temp']>=16)&(ww2009['temp']<22),'temp2']='좋음'
ww2009.loc[(ww2009['temp']>=22)&(ww2009['temp']<27),'temp2']='더움'
ww2009.loc[ww2009['temp'] >=27,'temp2']='매우더움'
ww2009 = pd.get_dummies(data=ww2009, columns=['temp2'], prefix='temp')
ww2009['humid2']=0
ww2009.loc[ww2009['humid'] < 30,'humid2']='건조'
ww2009.loc[(ww2009['humid']>=30)&(ww2009['humid']<41),'humid2']='쾌적'
ww2009.loc[(ww2009['humid']>=41)&(ww2009['humid']<52),'humid2']='보통'
ww2009.loc[(ww2009['humid']>=52)&(ww2009['humid']<60),'humid2']='불쾌'
ww2009.loc[ww2009['humid'] >=60,'humid2']='매우불쾌'
ww2009 = pd.get_dummies(data=ww2009, columns=['humid2'], prefix='체감습도')
ww2009['wind2']=0
ww2009.loc[ww2009['wind'] < 1,'wind2']='바람없음'
ww2009.loc[(ww2009['wind']>=1)&(ww2009['wind']<3),'wind2']='산들바람'
ww2009.loc[(ww2009['wind']>=3)&(ww2009['wind']<4),'wind2']='보통바람'
ww2009.loc[(ww2009['wind']>=4)&(ww2009['wind']<5),'wind2']='센바람'
ww2009.loc[ww2009['wind'] >=4,'wind2']='거센바람'
ww2009 = pd.get_dummies(data=ww2009, columns=['wind2'], prefix='바람')

In [0]:
ww2010.columns.values[0] = "when"
ww2010.columns.values[1] = "temp"
ww2010.columns.values[2] = "rain"
ww2010.columns.values[3] = "wind"
ww2010.columns.values[4] = "humid"
ww2010.columns.values[5] = "cloud"
ww2010 = ww2010.fillna(0)
#NAN값 0처리
ww2010['cloud2']=0
ww2010.loc[ww2010['cloud']<3,'cloud2']='맑음'
ww2010.loc[(ww2010['cloud']>=3)&(ww2010['cloud']< 6),'cloud2']='구름조금'
ww2010.loc[(ww2010['cloud']>=6)&(ww2010['cloud']<=9),'cloud2']='구름많음'
ww2010.loc[ww2010['cloud']>=9,'cloud2']='흐림'
ww2010['cloud2'].value_counts()
#총 365개값 확인
ww2010 = pd.get_dummies(data=ww2010, columns=['cloud2'], prefix='cloud')
ww2010[ww2010.isnull().any(axis=1)].head(5)
#혹시 누락된 데이터가 있는지 다시한번 출력해봄, 없는것같음
ww2010['temp2']=0
ww2010.loc[ww2010['temp'] < 4,'temp2']='매우추움'
ww2010.loc[(ww2010['temp']>=4)&(ww2010['temp']<8),'temp2']='추움'
ww2010.loc[(ww2010['temp']>=8)&(ww2010['temp']<11),'temp2']='쌀쌀'
ww2010.loc[(ww2010['temp']>=11)&(ww2010['temp']<16),'temp2']='선선'
ww2010.loc[(ww2010['temp']>=16)&(ww2010['temp']<22),'temp2']='좋음'
ww2010.loc[(ww2010['temp']>=22)&(ww2010['temp']<27),'temp2']='더움'
ww2010.loc[ww2010['temp'] >=27,'temp2']='매우더움'
ww2010 = pd.get_dummies(data=ww2010, columns=['temp2'], prefix='temp')
ww2010['humid2']=0
ww2010.loc[ww2010['humid'] < 30,'humid2']='건조'
ww2010.loc[(ww2010['humid']>=30)&(ww2010['humid']<41),'humid2']='쾌적'
ww2010.loc[(ww2010['humid']>=41)&(ww2010['humid']<52),'humid2']='보통'
ww2010.loc[(ww2010['humid']>=52)&(ww2010['humid']<60),'humid2']='불쾌'
ww2010.loc[ww2010['humid'] >=60,'humid2']='매우불쾌'
ww2010 = pd.get_dummies(data=ww2010, columns=['humid2'], prefix='체감습도')
ww2010['wind2']=0
ww2010.loc[ww2010['wind'] < 1,'wind2']='바람없음'
ww2010.loc[(ww2010['wind']>=1)&(ww2010['wind']<3),'wind2']='산들바람'
ww2010.loc[(ww2010['wind']>=3)&(ww2010['wind']<4),'wind2']='보통바람'
ww2010.loc[(ww2010['wind']>=4)&(ww2010['wind']<5),'wind2']='센바람'
ww2010.loc[ww2010['wind'] >=4,'wind2']='거센바람'
ww2010 = pd.get_dummies(data=ww2010, columns=['wind2'], prefix='바람')

In [0]:
ww2011.columns.values[0] = "when"
ww2011.columns.values[1] = "temp"
ww2011.columns.values[2] = "rain"
ww2011.columns.values[3] = "wind"
ww2011.columns.values[4] = "humid"
ww2011.columns.values[5] = "cloud"
ww2011 = ww2011.fillna(0)
#NAN값 0처리
ww2011['cloud2']=0
ww2011.loc[ww2011['cloud']<3,'cloud2']='맑음'
ww2011.loc[(ww2011['cloud']>=3)&(ww2011['cloud']< 6),'cloud2']='구름조금'
ww2011.loc[(ww2011['cloud']>=6)&(ww2011['cloud']<=9),'cloud2']='구름많음'
ww2011.loc[ww2011['cloud']>=9,'cloud2']='흐림'
ww2011['cloud2'].value_counts()
#총 365개값 확인
ww2011 = pd.get_dummies(data=ww2011, columns=['cloud2'], prefix='cloud')
ww2011[ww2011.isnull().any(axis=1)].head(5)
#혹시 누락된 데이터가 있는지 다시한번 출력해봄, 없는것같음
ww2011['temp2']=0
ww2011.loc[ww2011['temp'] < 4,'temp2']='매우추움'
ww2011.loc[(ww2011['temp']>=4)&(ww2011['temp']<8),'temp2']='추움'
ww2011.loc[(ww2011['temp']>=8)&(ww2011['temp']<11),'temp2']='쌀쌀'
ww2011.loc[(ww2011['temp']>=11)&(ww2011['temp']<16),'temp2']='선선'
ww2011.loc[(ww2011['temp']>=16)&(ww2011['temp']<22),'temp2']='좋음'
ww2011.loc[(ww2011['temp']>=22)&(ww2011['temp']<27),'temp2']='더움'
ww2011.loc[ww2011['temp'] >=27,'temp2']='매우더움'
ww2011 = pd.get_dummies(data=ww2011, columns=['temp2'], prefix='temp')
ww2011['humid2']=0
ww2011.loc[ww2011['humid'] < 30,'humid2']='건조'
ww2011.loc[(ww2011['humid']>=30)&(ww2011['humid']<41),'humid2']='쾌적'
ww2011.loc[(ww2011['humid']>=41)&(ww2011['humid']<52),'humid2']='보통'
ww2011.loc[(ww2011['humid']>=52)&(ww2011['humid']<60),'humid2']='불쾌'
ww2011.loc[ww2011['humid'] >=60,'humid2']='매우불쾌'
ww2011 = pd.get_dummies(data=ww2011, columns=['humid2'], prefix='체감습도')
ww2011['wind2']=0
ww2011.loc[ww2011['wind'] < 1,'wind2']='바람없음'
ww2011.loc[(ww2011['wind']>=1)&(ww2011['wind']<3),'wind2']='산들바람'
ww2011.loc[(ww2011['wind']>=3)&(ww2011['wind']<4),'wind2']='보통바람'
ww2011.loc[(ww2011['wind']>=4)&(ww2011['wind']<5),'wind2']='센바람'
ww2011.loc[ww2011['wind'] >=4,'wind2']='거센바람'
ww2011 = pd.get_dummies(data=ww2011, columns=['wind2'], prefix='바람')

In [0]:
ww2012.columns.values[0] = "when"
ww2012.columns.values[1] = "temp"
ww2012.columns.values[2] = "rain"
ww2012.columns.values[3] = "wind"
ww2012.columns.values[4] = "humid"
ww2012.columns.values[5] = "cloud"
ww2012 = ww2012.fillna(0)
#NAN값 0처리
ww2012['cloud2']=0
ww2012.loc[ww2012['cloud']<3,'cloud2']='맑음'
ww2012.loc[(ww2012['cloud']>=3)&(ww2012['cloud']< 6),'cloud2']='구름조금'
ww2012.loc[(ww2012['cloud']>=6)&(ww2012['cloud']<=9),'cloud2']='구름많음'
ww2012.loc[ww2012['cloud']>=9,'cloud2']='흐림'
ww2012['cloud2'].value_counts()
#총 365개값 확인
ww2012 = pd.get_dummies(data=ww2012, columns=['cloud2'], prefix='cloud')
ww2012[ww2012.isnull().any(axis=1)].head(5)
#혹시 누락된 데이터가 있는지 다시한번 출력해봄, 없는것같음
ww2012['temp2']=0
ww2012.loc[ww2012['temp'] < 4,'temp2']='매우추움'
ww2012.loc[(ww2012['temp']>=4)&(ww2012['temp']<8),'temp2']='추움'
ww2012.loc[(ww2012['temp']>=8)&(ww2012['temp']<11),'temp2']='쌀쌀'
ww2012.loc[(ww2012['temp']>=11)&(ww2012['temp']<16),'temp2']='선선'
ww2012.loc[(ww2012['temp']>=16)&(ww2012['temp']<22),'temp2']='좋음'
ww2012.loc[(ww2012['temp']>=22)&(ww2012['temp']<27),'temp2']='더움'
ww2012.loc[ww2012['temp'] >=27,'temp2']='매우더움'
ww2012 = pd.get_dummies(data=ww2012, columns=['temp2'], prefix='temp')
ww2012['humid2']=0
ww2012.loc[ww2012['humid'] < 30,'humid2']='건조'
ww2012.loc[(ww2012['humid']>=30)&(ww2012['humid']<41),'humid2']='쾌적'
ww2012.loc[(ww2012['humid']>=41)&(ww2012['humid']<52),'humid2']='보통'
ww2012.loc[(ww2012['humid']>=52)&(ww2012['humid']<60),'humid2']='불쾌'
ww2012.loc[ww2012['humid'] >=60,'humid2']='매우불쾌'
ww2012 = pd.get_dummies(data=ww2012, columns=['humid2'], prefix='체감습도')
ww2012['wind2']=0
ww2012.loc[ww2012['wind'] < 1,'wind2']='바람없음'
ww2012.loc[(ww2012['wind']>=1)&(ww2012['wind']<3),'wind2']='산들바람'
ww2012.loc[(ww2012['wind']>=3)&(ww2012['wind']<4),'wind2']='보통바람'
ww2012.loc[(ww2012['wind']>=4)&(ww2012['wind']<5),'wind2']='센바람'
ww2012.loc[ww2012['wind'] >=4,'wind2']='거센바람'
ww2012 = pd.get_dummies(data=ww2012, columns=['wind2'], prefix='바람')

In [0]:
ww2013.columns.values[0] = "when"
ww2013.columns.values[1] = "temp"
ww2013.columns.values[2] = "rain"
ww2013.columns.values[3] = "wind"
ww2013.columns.values[4] = "humid"
ww2013.columns.values[5] = "cloud"
ww2013 = ww2013.fillna(0)
#NAN값 0처리
ww2013['cloud2']=0
ww2013.loc[ww2013['cloud']<3,'cloud2']='맑음'
ww2013.loc[(ww2013['cloud']>=3)&(ww2013['cloud']< 6),'cloud2']='구름조금'
ww2013.loc[(ww2013['cloud']>=6)&(ww2013['cloud']<=9),'cloud2']='구름많음'
ww2013.loc[ww2013['cloud']>=9,'cloud2']='흐림'
ww2013['cloud2'].value_counts()
#총 365개값 확인
ww2013 = pd.get_dummies(data=ww2013, columns=['cloud2'], prefix='cloud')
ww2013[ww2013.isnull().any(axis=1)].head(5)
#혹시 누락된 데이터가 있는지 다시한번 출력해봄, 없는것같음
ww2013['temp2']=0
ww2013.loc[ww2013['temp'] < 4,'temp2']='매우추움'
ww2013.loc[(ww2013['temp']>=4)&(ww2013['temp']<8),'temp2']='추움'
ww2013.loc[(ww2013['temp']>=8)&(ww2013['temp']<11),'temp2']='쌀쌀'
ww2013.loc[(ww2013['temp']>=11)&(ww2013['temp']<16),'temp2']='선선'
ww2013.loc[(ww2013['temp']>=16)&(ww2013['temp']<22),'temp2']='좋음'
ww2013.loc[(ww2013['temp']>=22)&(ww2013['temp']<27),'temp2']='더움'
ww2013.loc[ww2013['temp'] >=27,'temp2']='매우더움'
ww2013 = pd.get_dummies(data=ww2013, columns=['temp2'], prefix='temp')
ww2013['humid2']=0
ww2013.loc[ww2013['humid'] < 30,'humid2']='건조'
ww2013.loc[(ww2013['humid']>=30)&(ww2013['humid']<41),'humid2']='쾌적'
ww2013.loc[(ww2013['humid']>=41)&(ww2013['humid']<52),'humid2']='보통'
ww2013.loc[(ww2013['humid']>=52)&(ww2013['humid']<60),'humid2']='불쾌'
ww2013.loc[ww2013['humid'] >=60,'humid2']='매우불쾌'
ww2013 = pd.get_dummies(data=ww2013, columns=['humid2'], prefix='체감습도')
ww2013['wind2']=0
ww2013.loc[ww2013['wind'] < 1,'wind2']='바람없음'
ww2013.loc[(ww2013['wind']>=1)&(ww2013['wind']<3),'wind2']='산들바람'
ww2013.loc[(ww2013['wind']>=3)&(ww2013['wind']<4),'wind2']='보통바람'
ww2013.loc[(ww2013['wind']>=4)&(ww2013['wind']<5),'wind2']='센바람'
ww2013.loc[ww2013['wind'] >=4,'wind2']='거센바람'
ww2013 = pd.get_dummies(data=ww2013, columns=['wind2'], prefix='바람')

In [0]:
ww2014.columns.values[0] = "when"
ww2014.columns.values[1] = "temp"
ww2014.columns.values[2] = "rain"
ww2014.columns.values[3] = "wind"
ww2014.columns.values[4] = "humid"
ww2014.columns.values[5] = "cloud"
ww2014 = ww2014.fillna(0)
#NAN값 0처리
ww2014['cloud2']=0
ww2014.loc[ww2014['cloud']<3,'cloud2']='맑음'
ww2014.loc[(ww2014['cloud']>=3)&(ww2014['cloud']< 6),'cloud2']='구름조금'
ww2014.loc[(ww2014['cloud']>=6)&(ww2014['cloud']<=9),'cloud2']='구름많음'
ww2014.loc[ww2014['cloud']>=9,'cloud2']='흐림'
ww2014['cloud2'].value_counts()
#총 365개값 확인
ww2014 = pd.get_dummies(data=ww2014, columns=['cloud2'], prefix='cloud')
ww2014[ww2014.isnull().any(axis=1)].head(5)
#혹시 누락된 데이터가 있는지 다시한번 출력해봄, 없는것같음
ww2014['temp2']=0
ww2014.loc[ww2014['temp'] < 4,'temp2']='매우추움'
ww2014.loc[(ww2014['temp']>=4)&(ww2014['temp']<8),'temp2']='추움'
ww2014.loc[(ww2014['temp']>=8)&(ww2014['temp']<11),'temp2']='쌀쌀'
ww2014.loc[(ww2014['temp']>=11)&(ww2014['temp']<16),'temp2']='선선'
ww2014.loc[(ww2014['temp']>=16)&(ww2014['temp']<22),'temp2']='좋음'
ww2014.loc[(ww2014['temp']>=22)&(ww2014['temp']<27),'temp2']='더움'
ww2014.loc[ww2014['temp'] >=27,'temp2']='매우더움'
ww2014 = pd.get_dummies(data=ww2014, columns=['temp2'], prefix='temp')
ww2014['humid2']=0
ww2014.loc[ww2014['humid'] < 30,'humid2']='건조'
ww2014.loc[(ww2014['humid']>=30)&(ww2014['humid']<41),'humid2']='쾌적'
ww2014.loc[(ww2014['humid']>=41)&(ww2014['humid']<52),'humid2']='보통'
ww2014.loc[(ww2014['humid']>=52)&(ww2014['humid']<60),'humid2']='불쾌'
ww2014.loc[ww2014['humid'] >=60,'humid2']='매우불쾌'
ww2014 = pd.get_dummies(data=ww2014, columns=['humid2'], prefix='체감습도')
ww2014['wind2']=0
ww2014.loc[ww2014['wind'] < 1,'wind2']='바람없음'
ww2014.loc[(ww2014['wind']>=1)&(ww2014['wind']<3),'wind2']='산들바람'
ww2014.loc[(ww2014['wind']>=3)&(ww2014['wind']<4),'wind2']='보통바람'
ww2014.loc[(ww2014['wind']>=4)&(ww2014['wind']<5),'wind2']='센바람'
ww2014.loc[ww2014['wind'] >=4,'wind2']='거센바람'
ww2014 = pd.get_dummies(data=ww2014, columns=['wind2'], prefix='바람')

In [0]:
ww2015.columns.values[0] = "when"
ww2015.columns.values[1] = "temp"
ww2015.columns.values[2] = "rain"
ww2015.columns.values[3] = "wind"
ww2015.columns.values[4] = "humid"
ww2015.columns.values[5] = "cloud"
ww2015 = ww2015.fillna(0)
#NAN값 0처리
ww2015['cloud2']=0
ww2015.loc[ww2015['cloud']<3,'cloud2']='맑음'
ww2015.loc[(ww2015['cloud']>=3)&(ww2015['cloud']< 6),'cloud2']='구름조금'
ww2015.loc[(ww2015['cloud']>=6)&(ww2015['cloud']<=9),'cloud2']='구름많음'
ww2015.loc[ww2015['cloud']>=9,'cloud2']='흐림'
ww2015['cloud2'].value_counts()
#총 365개값 확인
ww2015 = pd.get_dummies(data=ww2015, columns=['cloud2'], prefix='cloud')
ww2015[ww2015.isnull().any(axis=1)].head(5)
#혹시 누락된 데이터가 있는지 다시한번 출력해봄, 없는것같음
ww2015['temp2']=0
ww2015.loc[ww2015['temp'] < 4,'temp2']='매우추움'
ww2015.loc[(ww2015['temp']>=4)&(ww2015['temp']<8),'temp2']='추움'
ww2015.loc[(ww2015['temp']>=8)&(ww2015['temp']<11),'temp2']='쌀쌀'
ww2015.loc[(ww2015['temp']>=11)&(ww2015['temp']<16),'temp2']='선선'
ww2015.loc[(ww2015['temp']>=16)&(ww2015['temp']<22),'temp2']='좋음'
ww2015.loc[(ww2015['temp']>=22)&(ww2015['temp']<27),'temp2']='더움'
ww2015.loc[ww2015['temp'] >=27,'temp2']='매우더움'
ww2015 = pd.get_dummies(data=ww2015, columns=['temp2'], prefix='temp')
ww2015['humid2']=0
ww2015.loc[ww2015['humid'] < 30,'humid2']='건조'
ww2015.loc[(ww2015['humid']>=30)&(ww2015['humid']<41),'humid2']='쾌적'
ww2015.loc[(ww2015['humid']>=41)&(ww2015['humid']<52),'humid2']='보통'
ww2015.loc[(ww2015['humid']>=52)&(ww2015['humid']<60),'humid2']='불쾌'
ww2015.loc[ww2015['humid'] >=60,'humid2']='매우불쾌'
ww2015 = pd.get_dummies(data=ww2015, columns=['humid2'], prefix='체감습도')
ww2015['wind2']=0
ww2015.loc[ww2015['wind'] < 1,'wind2']='바람없음'
ww2015.loc[(ww2015['wind']>=1)&(ww2015['wind']<3),'wind2']='산들바람'
ww2015.loc[(ww2015['wind']>=3)&(ww2015['wind']<4),'wind2']='보통바람'
ww2015.loc[(ww2015['wind']>=4)&(ww2015['wind']<5),'wind2']='센바람'
ww2015.loc[ww2015['wind'] >=4,'wind2']='거센바람'
ww2015 = pd.get_dummies(data=ww2015, columns=['wind2'], prefix='바람')

In [0]:
ww2016.columns.values[0] = "when"
ww2016.columns.values[1] = "temp"
ww2016.columns.values[2] = "rain"
ww2016.columns.values[3] = "wind"
ww2016.columns.values[4] = "humid"
ww2016.columns.values[5] = "cloud"
ww2016 = ww2016.fillna(0)
#NAN값 0처리
ww2016['cloud2']=0
ww2016.loc[ww2016['cloud']<3,'cloud2']='맑음'
ww2016.loc[(ww2016['cloud']>=3)&(ww2016['cloud']< 6),'cloud2']='구름조금'
ww2016.loc[(ww2016['cloud']>=6)&(ww2016['cloud']<=9),'cloud2']='구름많음'
ww2016.loc[ww2016['cloud']>=9,'cloud2']='흐림'
ww2016['cloud2'].value_counts()
#총 365개값 확인
ww2016 = pd.get_dummies(data=ww2016, columns=['cloud2'], prefix='cloud')
ww2016[ww2016.isnull().any(axis=1)].head(5)
#혹시 누락된 데이터가 있는지 다시한번 출력해봄, 없는것같음
ww2016['temp2']=0
ww2016.loc[ww2016['temp'] < 4,'temp2']='매우추움'
ww2016.loc[(ww2016['temp']>=4)&(ww2016['temp']<8),'temp2']='추움'
ww2016.loc[(ww2016['temp']>=8)&(ww2016['temp']<11),'temp2']='쌀쌀'
ww2016.loc[(ww2016['temp']>=11)&(ww2016['temp']<16),'temp2']='선선'
ww2016.loc[(ww2016['temp']>=16)&(ww2016['temp']<22),'temp2']='좋음'
ww2016.loc[(ww2016['temp']>=22)&(ww2016['temp']<27),'temp2']='더움'
ww2016.loc[ww2016['temp'] >=27,'temp2']='매우더움'
ww2016 = pd.get_dummies(data=ww2016, columns=['temp2'], prefix='temp')
ww2016['humid2']=0
ww2016.loc[ww2016['humid'] < 30,'humid2']='건조'
ww2016.loc[(ww2016['humid']>=30)&(ww2016['humid']<41),'humid2']='쾌적'
ww2016.loc[(ww2016['humid']>=41)&(ww2016['humid']<52),'humid2']='보통'
ww2016.loc[(ww2016['humid']>=52)&(ww2016['humid']<60),'humid2']='불쾌'
ww2016.loc[ww2016['humid'] >=60,'humid2']='매우불쾌'
ww2016 = pd.get_dummies(data=ww2016, columns=['humid2'], prefix='체감습도')
ww2016['wind2']=0
ww2016.loc[ww2016['wind'] < 1,'wind2']='바람없음'
ww2016.loc[(ww2016['wind']>=1)&(ww2016['wind']<3),'wind2']='산들바람'
ww2016.loc[(ww2016['wind']>=3)&(ww2016['wind']<4),'wind2']='보통바람'
ww2016.loc[(ww2016['wind']>=4)&(ww2016['wind']<5),'wind2']='센바람'
ww2016.loc[ww2016['wind'] >=4,'wind2']='거센바람'
ww2016 = pd.get_dummies(data=ww2016, columns=['wind2'], prefix='바람')

In [0]:
ww2017.columns.values[0] = "when"
ww2017.columns.values[1] = "temp"
ww2017.columns.values[2] = "rain"
ww2017.columns.values[3] = "wind"
ww2017.columns.values[4] = "humid"
ww2017.columns.values[5] = "cloud"
ww2017 = ww2017.fillna(0)
#NAN값 0처리
ww2017['cloud2']=0
ww2017.loc[ww2017['cloud']<3,'cloud2']='맑음'
ww2017.loc[(ww2017['cloud']>=3)&(ww2017['cloud']< 6),'cloud2']='구름조금'
ww2017.loc[(ww2017['cloud']>=6)&(ww2017['cloud']<=9),'cloud2']='구름많음'
ww2017.loc[ww2017['cloud']>=9,'cloud2']='흐림'
ww2017['cloud2'].value_counts()
#총 365개값 확인
ww2017 = pd.get_dummies(data=ww2017, columns=['cloud2'], prefix='cloud')
ww2017[ww2017.isnull().any(axis=1)].head(5)
#혹시 누락된 데이터가 있는지 다시한번 출력해봄, 없는것같음
ww2017['temp2']=0
ww2017.loc[ww2017['temp'] < 4,'temp2']='매우추움'
ww2017.loc[(ww2017['temp']>=4)&(ww2017['temp']<8),'temp2']='추움'
ww2017.loc[(ww2017['temp']>=8)&(ww2017['temp']<11),'temp2']='쌀쌀'
ww2017.loc[(ww2017['temp']>=11)&(ww2017['temp']<16),'temp2']='선선'
ww2017.loc[(ww2017['temp']>=16)&(ww2017['temp']<22),'temp2']='좋음'
ww2017.loc[(ww2017['temp']>=22)&(ww2017['temp']<27),'temp2']='더움'
ww2017.loc[ww2017['temp'] >=27,'temp2']='매우더움'
ww2017 = pd.get_dummies(data=ww2017, columns=['temp2'], prefix='temp')
ww2017['humid2']=0
ww2017.loc[ww2017['humid'] < 30,'humid2']='건조'
ww2017.loc[(ww2017['humid']>=30)&(ww2017['humid']<41),'humid2']='쾌적'
ww2017.loc[(ww2017['humid']>=41)&(ww2017['humid']<52),'humid2']='보통'
ww2017.loc[(ww2017['humid']>=52)&(ww2017['humid']<60),'humid2']='불쾌'
ww2017.loc[ww2017['humid'] >=60,'humid2']='매우불쾌'
ww2017 = pd.get_dummies(data=ww2017, columns=['humid2'], prefix='체감습도')
ww2017['wind2']=0
ww2017.loc[ww2017['wind'] < 1,'wind2']='바람없음'
ww2017.loc[(ww2017['wind']>=1)&(ww2017['wind']<3),'wind2']='산들바람'
ww2017.loc[(ww2017['wind']>=3)&(ww2017['wind']<4),'wind2']='보통바람'
ww2017.loc[(ww2017['wind']>=4)&(ww2017['wind']<5),'wind2']='센바람'
ww2017.loc[ww2017['wind'] >=4,'wind2']='거센바람'
ww2017 = pd.get_dummies(data=ww2017, columns=['wind2'], prefix='바람')

In [0]:
ww2018.columns.values[0] = "when"
ww2018.columns.values[1] = "temp"
ww2018.columns.values[2] = "rain"
ww2018.columns.values[3] = "wind"
ww2018.columns.values[4] = "humid"
ww2018.columns.values[5] = "cloud"
ww2018 = ww2018.fillna(0)
#NAN값 0처리
ww2018['cloud2']=0
ww2018.loc[ww2018['cloud']<3,'cloud2']='맑음'
ww2018.loc[(ww2018['cloud']>=3)&(ww2018['cloud']< 6),'cloud2']='구름조금'
ww2018.loc[(ww2018['cloud']>=6)&(ww2018['cloud']<=9),'cloud2']='구름많음'
ww2018.loc[ww2018['cloud']>=9,'cloud2']='흐림'
ww2018['cloud2'].value_counts()
#총 365개값 확인
ww2018 = pd.get_dummies(data=ww2018, columns=['cloud2'], prefix='cloud')
ww2018[ww2018.isnull().any(axis=1)].head(5)
#혹시 누락된 데이터가 있는지 다시한번 출력해봄, 없는것같음
ww2018['temp2']=0
ww2018.loc[ww2018['temp'] < 4,'temp2']='매우추움'
ww2018.loc[(ww2018['temp']>=4)&(ww2018['temp']<8),'temp2']='추움'
ww2018.loc[(ww2018['temp']>=8)&(ww2018['temp']<11),'temp2']='쌀쌀'
ww2018.loc[(ww2018['temp']>=11)&(ww2018['temp']<16),'temp2']='선선'
ww2018.loc[(ww2018['temp']>=16)&(ww2018['temp']<22),'temp2']='좋음'
ww2018.loc[(ww2018['temp']>=22)&(ww2018['temp']<27),'temp2']='더움'
ww2018.loc[ww2018['temp'] >=27,'temp2']='매우더움'
ww2018 = pd.get_dummies(data=ww2018, columns=['temp2'], prefix='temp')
ww2018['humid2']=0
ww2018.loc[ww2018['humid'] < 30,'humid2']='건조'
ww2018.loc[(ww2018['humid']>=30)&(ww2018['humid']<41),'humid2']='쾌적'
ww2018.loc[(ww2018['humid']>=41)&(ww2018['humid']<52),'humid2']='보통'
ww2018.loc[(ww2018['humid']>=52)&(ww2018['humid']<60),'humid2']='불쾌'
ww2018.loc[ww2018['humid'] >=60,'humid2']='매우불쾌'
ww2018 = pd.get_dummies(data=ww2018, columns=['humid2'], prefix='체감습도')
ww2018['wind2']=0
ww2018.loc[ww2018['wind'] < 1,'wind2']='바람없음'
ww2018.loc[(ww2018['wind']>=1)&(ww2018['wind']<3),'wind2']='산들바람'
ww2018.loc[(ww2018['wind']>=3)&(ww2018['wind']<4),'wind2']='보통바람'
ww2018.loc[(ww2018['wind']>=4)&(ww2018['wind']<5),'wind2']='센바람'
ww2018.loc[ww2018['wind'] >=4,'wind2']='거센바람'
ww2018 = pd.get_dummies(data=ww2018, columns=['wind2'], prefix='바람')

In [0]:
ww2019.columns.values[0] = "when"
ww2019.columns.values[1] = "temp"
ww2019.columns.values[2] = "rain"
ww2019.columns.values[3] = "wind"
ww2019.columns.values[4] = "humid"
ww2019.columns.values[5] = "cloud"
ww2019 = ww2019.fillna(0)
#NAN값 0처리
ww2019['cloud2']=0
ww2019.loc[ww2019['cloud']<3,'cloud2']='맑음'
ww2019.loc[(ww2019['cloud']>=3)&(ww2019['cloud']< 6),'cloud2']='구름조금'
ww2019.loc[(ww2019['cloud']>=6)&(ww2019['cloud']<=9),'cloud2']='구름많음'
ww2019.loc[ww2019['cloud']>=9,'cloud2']='흐림'
ww2019['cloud2'].value_counts()
#총 365개값 확인
ww2019 = pd.get_dummies(data=ww2019, columns=['cloud2'], prefix='cloud')
ww2019[ww2019.isnull().any(axis=1)].head(5)
#혹시 누락된 데이터가 있는지 다시한번 출력해봄, 없는것같음
ww2019['temp2']=0
ww2019.loc[ww2019['temp'] < 4,'temp2']='매우추움'
ww2019.loc[(ww2019['temp']>=4)&(ww2019['temp']<8),'temp2']='추움'
ww2019.loc[(ww2019['temp']>=8)&(ww2019['temp']<11),'temp2']='쌀쌀'
ww2019.loc[(ww2019['temp']>=11)&(ww2019['temp']<16),'temp2']='선선'
ww2019.loc[(ww2019['temp']>=16)&(ww2019['temp']<22),'temp2']='좋음'
ww2019.loc[(ww2019['temp']>=22)&(ww2019['temp']<27),'temp2']='더움'
ww2019.loc[ww2019['temp'] >=27,'temp2']='매우더움'
ww2019 = pd.get_dummies(data=ww2019, columns=['temp2'], prefix='temp')
ww2019['humid2']=0
ww2019.loc[ww2019['humid'] < 30,'humid2']='건조'
ww2019.loc[(ww2019['humid']>=30)&(ww2019['humid']<41),'humid2']='쾌적'
ww2019.loc[(ww2019['humid']>=41)&(ww2019['humid']<52),'humid2']='보통'
ww2019.loc[(ww2019['humid']>=52)&(ww2019['humid']<60),'humid2']='불쾌'
ww2019.loc[ww2019['humid'] >=60,'humid2']='매우불쾌'
ww2019 = pd.get_dummies(data=ww2019, columns=['humid2'], prefix='체감습도')
ww2019['wind2']=0
ww2019.loc[ww2019['wind'] < 1,'wind2']='바람없음'
ww2019.loc[(ww2019['wind']>=1)&(ww2019['wind']<3),'wind2']='산들바람'
ww2019.loc[(ww2019['wind']>=3)&(ww2019['wind']<4),'wind2']='보통바람'
ww2019.loc[(ww2019['wind']>=4)&(ww2019['wind']<5),'wind2']='센바람'
ww2019.loc[ww2019['wind'] >=4,'wind2']='거센바람'
ww2019 = pd.get_dummies(data=ww2019, columns=['wind2'], prefix='바람')
ww2019

           when  temp  rain  wind  ...  바람_거센바람  바람_바람없음  바람_보통바람  바람_산들바람
0    2019-01-01  -5.0   0.0   2.1  ...        0        0        0        1
1    2019-01-02  -4.9   0.0   1.7  ...        0        0        0        1
2    2019-01-03  -3.5   0.0   1.4  ...        0        0        0        1
3    2019-01-04  -1.1   0.0   1.2  ...        0        0        0        1
4    2019-01-05  -2.8   0.0   2.2  ...        0        0        0        1
..          ...   ...   ...   ...  ...      ...      ...      ...      ...
341  2019-12-08  -0.9   0.0   1.4  ...        0        0        0        1
342  2019-12-09   3.2   0.0   2.5  ...        0        0        0        1
343  2019-12-10   8.1   1.7   1.2  ...        0        0        0        1
344  2019-12-11   6.3   0.2   3.4  ...        0        0        1        0
345  2019-12-12  -0.7   0.0   1.8  ...        0        0        0        1

[346 rows x 30 columns]

In [0]:
# ******************************************************** 1 2 3 4 추가 4가지

In [0]:
ww2006['cloud_1234_4isMax']=0
ww2006.loc[ww2006['cloud']<3,'cloud_1234_4isMax']='1'
ww2006.loc[(ww2006['cloud']>=3)&(ww2006['cloud']< 6),'cloud_1234_4isMax']='2'
ww2006.loc[(ww2006['cloud']>=6)&(ww2006['cloud']<=9),'cloud_1234_4isMax']='3'
ww2006.loc[ww2006['cloud']>=9,'cloud_1234_4isMax']='4'
ww2006['temp1to7_7isMax']=0
ww2006.loc[ww2006['temp'] < 4,'temp1to7_7isMax']=1
ww2006.loc[(ww2006['temp']>=4)&(ww2006['temp']<8),'temp1to7_7isMax']=2
ww2006.loc[(ww2006['temp']>=8)&(ww2006['temp']<11),'temp1to7_7isMax']=3
ww2006.loc[(ww2006['temp']>=11)&(ww2006['temp']<16),'temp1to7_7isMax']=4
ww2006.loc[(ww2006['temp']>=16)&(ww2006['temp']<22),'temp1to7_7isMax']=5
ww2006.loc[(ww2006['temp']>=22)&(ww2006['temp']<27),'temp1to7_7isMax']=6
ww2006.loc[ww2006['temp'] >=27,'temp1to7_7isMax']=7
ww2006['humid1to5_5isMax']=0
ww2006.loc[ww2006['humid'] < 30,'humid1to5_5isMax']=1
ww2006.loc[(ww2006['humid']>=30)&(ww2006['humid']<41),'humid1to5_5isMax']=2
ww2006.loc[(ww2006['humid']>=41)&(ww2006['humid']<52),'humid1to5_5isMax']=3
ww2006.loc[(ww2006['humid']>=52)&(ww2006['humid']<60),'humid1to5_5isMax']=4
ww2006.loc[ww2006['humid'] >=60,'humid1to5_5isMax']=5
ww2006['wind1to5_5isStrong']=0
ww2006.loc[ww2006['wind'] < 1,'wind1to5_5isStrong']=0
ww2006.loc[(ww2006['wind']>=1)&(ww2006['wind']<3),'wind1to5_5isStrong']=1
ww2006.loc[(ww2006['wind']>=3)&(ww2006['wind']<4),'wind1to5_5isStrong']=2
ww2006.loc[(ww2006['wind']>=4)&(ww2006['wind']<5),'wind1to5_5isStrong']=3
ww2006.loc[ww2006['wind'] >=4,'wind1to5_5isStrong']=4

In [0]:
ww2007['cloud_1234_4isMax']=0
ww2007.loc[ww2007['cloud']<3,'cloud_1234_4isMax']='1'
ww2007.loc[(ww2007['cloud']>=3)&(ww2007['cloud']< 6),'cloud_1234_4isMax']='2'
ww2007.loc[(ww2007['cloud']>=6)&(ww2007['cloud']<=9),'cloud_1234_4isMax']='3'
ww2007.loc[ww2007['cloud']>=9,'cloud_1234_4isMax']='4'
ww2007['temp1to7_7isMax']=0
ww2007.loc[ww2007['temp'] < 4,'temp1to7_7isMax']=1
ww2007.loc[(ww2007['temp']>=4)&(ww2007['temp']<8),'temp1to7_7isMax']=2
ww2007.loc[(ww2007['temp']>=8)&(ww2007['temp']<11),'temp1to7_7isMax']=3
ww2007.loc[(ww2007['temp']>=11)&(ww2007['temp']<16),'temp1to7_7isMax']=4
ww2007.loc[(ww2007['temp']>=16)&(ww2007['temp']<22),'temp1to7_7isMax']=5
ww2007.loc[(ww2007['temp']>=22)&(ww2007['temp']<27),'temp1to7_7isMax']=6
ww2007.loc[ww2007['temp'] >=27,'temp1to7_7isMax']=7
ww2007['humid1to5_5isMax']=0
ww2007.loc[ww2007['humid'] < 30,'humid1to5_5isMax']=1
ww2007.loc[(ww2007['humid']>=30)&(ww2007['humid']<41),'humid1to5_5isMax']=2
ww2007.loc[(ww2007['humid']>=41)&(ww2007['humid']<52),'humid1to5_5isMax']=3
ww2007.loc[(ww2007['humid']>=52)&(ww2007['humid']<60),'humid1to5_5isMax']=4
ww2007.loc[ww2007['humid'] >=60,'humid1to5_5isMax']=5
ww2007['wind1to5_5isStrong']=0
ww2007.loc[ww2007['wind'] < 1,'wind1to5_5isStrong']=0
ww2007.loc[(ww2007['wind']>=1)&(ww2007['wind']<3),'wind1to5_5isStrong']=1
ww2007.loc[(ww2007['wind']>=3)&(ww2007['wind']<4),'wind1to5_5isStrong']=2
ww2007.loc[(ww2007['wind']>=4)&(ww2007['wind']<5),'wind1to5_5isStrong']=3
ww2007.loc[ww2007['wind'] >=4,'wind1to5_5isStrong']=4

In [0]:
ww2008['cloud_1234_4isMax']=0
ww2008.loc[ww2008['cloud']<3,'cloud_1234_4isMax']='1'
ww2008.loc[(ww2008['cloud']>=3)&(ww2008['cloud']< 6),'cloud_1234_4isMax']='2'
ww2008.loc[(ww2008['cloud']>=6)&(ww2008['cloud']<=9),'cloud_1234_4isMax']='3'
ww2008.loc[ww2008['cloud']>=9,'cloud_1234_4isMax']='4'
ww2008['temp1to7_7isMax']=0
ww2008.loc[ww2008['temp'] < 4,'temp1to7_7isMax']=1
ww2008.loc[(ww2008['temp']>=4)&(ww2008['temp']<8),'temp1to7_7isMax']=2
ww2008.loc[(ww2008['temp']>=8)&(ww2008['temp']<11),'temp1to7_7isMax']=3
ww2008.loc[(ww2008['temp']>=11)&(ww2008['temp']<16),'temp1to7_7isMax']=4
ww2008.loc[(ww2008['temp']>=16)&(ww2008['temp']<22),'temp1to7_7isMax']=5
ww2008.loc[(ww2008['temp']>=22)&(ww2008['temp']<27),'temp1to7_7isMax']=6
ww2008.loc[ww2008['temp'] >=27,'temp1to7_7isMax']=7
ww2008['humid1to5_5isMax']=0
ww2008.loc[ww2008['humid'] < 30,'humid1to5_5isMax']=1
ww2008.loc[(ww2008['humid']>=30)&(ww2008['humid']<41),'humid1to5_5isMax']=2
ww2008.loc[(ww2008['humid']>=41)&(ww2008['humid']<52),'humid1to5_5isMax']=3
ww2008.loc[(ww2008['humid']>=52)&(ww2008['humid']<60),'humid1to5_5isMax']=4
ww2008.loc[ww2008['humid'] >=60,'humid1to5_5isMax']=5
ww2008['wind1to5_5isStrong']=0
ww2008.loc[ww2008['wind'] < 1,'wind1to5_5isStrong']=0
ww2008.loc[(ww2008['wind']>=1)&(ww2008['wind']<3),'wind1to5_5isStrong']=1
ww2008.loc[(ww2008['wind']>=3)&(ww2008['wind']<4),'wind1to5_5isStrong']=2
ww2008.loc[(ww2008['wind']>=4)&(ww2008['wind']<5),'wind1to5_5isStrong']=3
ww2008.loc[ww2008['wind'] >=4,'wind1to5_5isStrong']=4

In [0]:
ww2009['cloud_1234_4isMax']=0
ww2009.loc[ww2009['cloud']<3,'cloud_1234_4isMax']='1'
ww2009.loc[(ww2009['cloud']>=3)&(ww2009['cloud']< 6),'cloud_1234_4isMax']='2'
ww2009.loc[(ww2009['cloud']>=6)&(ww2009['cloud']<=9),'cloud_1234_4isMax']='3'
ww2009.loc[ww2009['cloud']>=9,'cloud_1234_4isMax']='4'
ww2009['temp1to7_7isMax']=0
ww2009.loc[ww2009['temp'] < 4,'temp1to7_7isMax']=1
ww2009.loc[(ww2009['temp']>=4)&(ww2009['temp']<8),'temp1to7_7isMax']=2
ww2009.loc[(ww2009['temp']>=8)&(ww2009['temp']<11),'temp1to7_7isMax']=3
ww2009.loc[(ww2009['temp']>=11)&(ww2009['temp']<16),'temp1to7_7isMax']=4
ww2009.loc[(ww2009['temp']>=16)&(ww2009['temp']<22),'temp1to7_7isMax']=5
ww2009.loc[(ww2009['temp']>=22)&(ww2009['temp']<27),'temp1to7_7isMax']=6
ww2009.loc[ww2009['temp'] >=27,'temp1to7_7isMax']=7
ww2009['humid1to5_5isMax']=0
ww2009.loc[ww2009['humid'] < 30,'humid1to5_5isMax']=1
ww2009.loc[(ww2009['humid']>=30)&(ww2009['humid']<41),'humid1to5_5isMax']=2
ww2009.loc[(ww2009['humid']>=41)&(ww2009['humid']<52),'humid1to5_5isMax']=3
ww2009.loc[(ww2009['humid']>=52)&(ww2009['humid']<60),'humid1to5_5isMax']=4
ww2009.loc[ww2009['humid'] >=60,'humid1to5_5isMax']=5
ww2009['wind1to5_5isStrong']=0
ww2009.loc[ww2009['wind'] < 1,'wind1to5_5isStrong']=0
ww2009.loc[(ww2009['wind']>=1)&(ww2009['wind']<3),'wind1to5_5isStrong']=1
ww2009.loc[(ww2009['wind']>=3)&(ww2009['wind']<4),'wind1to5_5isStrong']=2
ww2009.loc[(ww2009['wind']>=4)&(ww2009['wind']<5),'wind1to5_5isStrong']=3
ww2009.loc[ww2009['wind'] >=4,'wind1to5_5isStrong']=4

In [0]:
ww2010['cloud_1234_4isMax']=0
ww2010.loc[ww2010['cloud']<3,'cloud_1234_4isMax']='1'
ww2010.loc[(ww2010['cloud']>=3)&(ww2010['cloud']< 6),'cloud_1234_4isMax']='2'
ww2010.loc[(ww2010['cloud']>=6)&(ww2010['cloud']<=9),'cloud_1234_4isMax']='3'
ww2010.loc[ww2010['cloud']>=9,'cloud_1234_4isMax']='4'
ww2010['temp1to7_7isMax']=0
ww2010.loc[ww2010['temp'] < 4,'temp1to7_7isMax']=1
ww2010.loc[(ww2010['temp']>=4)&(ww2010['temp']<8),'temp1to7_7isMax']=2
ww2010.loc[(ww2010['temp']>=8)&(ww2010['temp']<11),'temp1to7_7isMax']=3
ww2010.loc[(ww2010['temp']>=11)&(ww2010['temp']<16),'temp1to7_7isMax']=4
ww2010.loc[(ww2010['temp']>=16)&(ww2010['temp']<22),'temp1to7_7isMax']=5
ww2010.loc[(ww2010['temp']>=22)&(ww2010['temp']<27),'temp1to7_7isMax']=6
ww2010.loc[ww2010['temp'] >=27,'temp1to7_7isMax']=7
ww2010['humid1to5_5isMax']=0
ww2010.loc[ww2010['humid'] < 30,'humid1to5_5isMax']=1
ww2010.loc[(ww2010['humid']>=30)&(ww2010['humid']<41),'humid1to5_5isMax']=2
ww2010.loc[(ww2010['humid']>=41)&(ww2010['humid']<52),'humid1to5_5isMax']=3
ww2010.loc[(ww2010['humid']>=52)&(ww2010['humid']<60),'humid1to5_5isMax']=4
ww2010.loc[ww2010['humid'] >=60,'humid1to5_5isMax']=5
ww2010['wind1to5_5isStrong']=0
ww2010.loc[ww2010['wind'] < 1,'wind1to5_5isStrong']=0
ww2010.loc[(ww2010['wind']>=1)&(ww2010['wind']<3),'wind1to5_5isStrong']=1
ww2010.loc[(ww2010['wind']>=3)&(ww2010['wind']<4),'wind1to5_5isStrong']=2
ww2010.loc[(ww2010['wind']>=4)&(ww2010['wind']<5),'wind1to5_5isStrong']=3
ww2010.loc[ww2010['wind'] >=4,'wind1to5_5isStrong']=4

In [0]:
ww2011['cloud_1234_4isMax']=0
ww2011.loc[ww2011['cloud']<3,'cloud_1234_4isMax']='1'
ww2011.loc[(ww2011['cloud']>=3)&(ww2011['cloud']< 6),'cloud_1234_4isMax']='2'
ww2011.loc[(ww2011['cloud']>=6)&(ww2011['cloud']<=9),'cloud_1234_4isMax']='3'
ww2011.loc[ww2011['cloud']>=9,'cloud_1234_4isMax']='4'
ww2011['temp1to7_7isMax']=0
ww2011.loc[ww2011['temp'] < 4,'temp1to7_7isMax']=1
ww2011.loc[(ww2011['temp']>=4)&(ww2011['temp']<8),'temp1to7_7isMax']=2
ww2011.loc[(ww2011['temp']>=8)&(ww2011['temp']<11),'temp1to7_7isMax']=3
ww2011.loc[(ww2011['temp']>=11)&(ww2011['temp']<16),'temp1to7_7isMax']=4
ww2011.loc[(ww2011['temp']>=16)&(ww2011['temp']<22),'temp1to7_7isMax']=5
ww2011.loc[(ww2011['temp']>=22)&(ww2011['temp']<27),'temp1to7_7isMax']=6
ww2011.loc[ww2011['temp'] >=27,'temp1to7_7isMax']=7
ww2011['humid1to5_5isMax']=0
ww2011.loc[ww2011['humid'] < 30,'humid1to5_5isMax']=1
ww2011.loc[(ww2011['humid']>=30)&(ww2011['humid']<41),'humid1to5_5isMax']=2
ww2011.loc[(ww2011['humid']>=41)&(ww2011['humid']<52),'humid1to5_5isMax']=3
ww2011.loc[(ww2011['humid']>=52)&(ww2011['humid']<60),'humid1to5_5isMax']=4
ww2011.loc[ww2011['humid'] >=60,'humid1to5_5isMax']=5
ww2011['wind1to5_5isStrong']=0
ww2011.loc[ww2011['wind'] < 1,'wind1to5_5isStrong']=0
ww2011.loc[(ww2011['wind']>=1)&(ww2011['wind']<3),'wind1to5_5isStrong']=1
ww2011.loc[(ww2011['wind']>=3)&(ww2011['wind']<4),'wind1to5_5isStrong']=2
ww2011.loc[(ww2011['wind']>=4)&(ww2011['wind']<5),'wind1to5_5isStrong']=3
ww2011.loc[ww2011['wind'] >=4,'wind1to5_5isStrong']=4

In [0]:
ww2012['cloud_1234_4isMax']=0
ww2012.loc[ww2012['cloud']<3,'cloud_1234_4isMax']='1'
ww2012.loc[(ww2012['cloud']>=3)&(ww2012['cloud']< 6),'cloud_1234_4isMax']='2'
ww2012.loc[(ww2012['cloud']>=6)&(ww2012['cloud']<=9),'cloud_1234_4isMax']='3'
ww2012.loc[ww2012['cloud']>=9,'cloud_1234_4isMax']='4'
ww2012['temp1to7_7isMax']=0
ww2012.loc[ww2012['temp'] < 4,'temp1to7_7isMax']=1
ww2012.loc[(ww2012['temp']>=4)&(ww2012['temp']<8),'temp1to7_7isMax']=2
ww2012.loc[(ww2012['temp']>=8)&(ww2012['temp']<11),'temp1to7_7isMax']=3
ww2012.loc[(ww2012['temp']>=11)&(ww2012['temp']<16),'temp1to7_7isMax']=4
ww2012.loc[(ww2012['temp']>=16)&(ww2012['temp']<22),'temp1to7_7isMax']=5
ww2012.loc[(ww2012['temp']>=22)&(ww2012['temp']<27),'temp1to7_7isMax']=6
ww2012.loc[ww2012['temp'] >=27,'temp1to7_7isMax']=7
ww2012['humid1to5_5isMax']=0
ww2012.loc[ww2012['humid'] < 30,'humid1to5_5isMax']=1
ww2012.loc[(ww2012['humid']>=30)&(ww2012['humid']<41),'humid1to5_5isMax']=2
ww2012.loc[(ww2012['humid']>=41)&(ww2012['humid']<52),'humid1to5_5isMax']=3
ww2012.loc[(ww2012['humid']>=52)&(ww2012['humid']<60),'humid1to5_5isMax']=4
ww2012.loc[ww2012['humid'] >=60,'humid1to5_5isMax']=5
ww2012['wind1to5_5isStrong']=0
ww2012.loc[ww2012['wind'] < 1,'wind1to5_5isStrong']=0
ww2012.loc[(ww2012['wind']>=1)&(ww2012['wind']<3),'wind1to5_5isStrong']=1
ww2012.loc[(ww2012['wind']>=3)&(ww2012['wind']<4),'wind1to5_5isStrong']=2
ww2012.loc[(ww2012['wind']>=4)&(ww2012['wind']<5),'wind1to5_5isStrong']=3
ww2012.loc[ww2012['wind'] >=4,'wind1to5_5isStrong']=4

In [0]:
ww2013['cloud_1234_4isMax']=0
ww2013.loc[ww2013['cloud']<3,'cloud_1234_4isMax']='1'
ww2013.loc[(ww2013['cloud']>=3)&(ww2013['cloud']< 6),'cloud_1234_4isMax']='2'
ww2013.loc[(ww2013['cloud']>=6)&(ww2013['cloud']<=9),'cloud_1234_4isMax']='3'
ww2013.loc[ww2013['cloud']>=9,'cloud_1234_4isMax']='4'
ww2013['temp1to7_7isMax']=0
ww2013.loc[ww2013['temp'] < 4,'temp1to7_7isMax']=1
ww2013.loc[(ww2013['temp']>=4)&(ww2013['temp']<8),'temp1to7_7isMax']=2
ww2013.loc[(ww2013['temp']>=8)&(ww2013['temp']<11),'temp1to7_7isMax']=3
ww2013.loc[(ww2013['temp']>=11)&(ww2013['temp']<16),'temp1to7_7isMax']=4
ww2013.loc[(ww2013['temp']>=16)&(ww2013['temp']<22),'temp1to7_7isMax']=5
ww2013.loc[(ww2013['temp']>=22)&(ww2013['temp']<27),'temp1to7_7isMax']=6
ww2013.loc[ww2013['temp'] >=27,'temp1to7_7isMax']=7
ww2013['humid1to5_5isMax']=0
ww2013.loc[ww2013['humid'] < 30,'humid1to5_5isMax']=1
ww2013.loc[(ww2013['humid']>=30)&(ww2013['humid']<41),'humid1to5_5isMax']=2
ww2013.loc[(ww2013['humid']>=41)&(ww2013['humid']<52),'humid1to5_5isMax']=3
ww2013.loc[(ww2013['humid']>=52)&(ww2013['humid']<60),'humid1to5_5isMax']=4
ww2013.loc[ww2013['humid'] >=60,'humid1to5_5isMax']=5
ww2013['wind1to5_5isStrong']=0
ww2013.loc[ww2013['wind'] < 1,'wind1to5_5isStrong']=0
ww2013.loc[(ww2013['wind']>=1)&(ww2013['wind']<3),'wind1to5_5isStrong']=1
ww2013.loc[(ww2013['wind']>=3)&(ww2013['wind']<4),'wind1to5_5isStrong']=2
ww2013.loc[(ww2013['wind']>=4)&(ww2013['wind']<5),'wind1to5_5isStrong']=3
ww2013.loc[ww2013['wind'] >=4,'wind1to5_5isStrong']=4

In [0]:
ww2014['cloud_1234_4isMax']=0
ww2014.loc[ww2014['cloud']<3,'cloud_1234_4isMax']='1'
ww2014.loc[(ww2014['cloud']>=3)&(ww2014['cloud']< 6),'cloud_1234_4isMax']='2'
ww2014.loc[(ww2014['cloud']>=6)&(ww2014['cloud']<=9),'cloud_1234_4isMax']='3'
ww2014.loc[ww2014['cloud']>=9,'cloud_1234_4isMax']='4'
ww2014['temp1to7_7isMax']=0
ww2014.loc[ww2014['temp'] < 4,'temp1to7_7isMax']=1
ww2014.loc[(ww2014['temp']>=4)&(ww2014['temp']<8),'temp1to7_7isMax']=2
ww2014.loc[(ww2014['temp']>=8)&(ww2014['temp']<11),'temp1to7_7isMax']=3
ww2014.loc[(ww2014['temp']>=11)&(ww2014['temp']<16),'temp1to7_7isMax']=4
ww2014.loc[(ww2014['temp']>=16)&(ww2014['temp']<22),'temp1to7_7isMax']=5
ww2014.loc[(ww2014['temp']>=22)&(ww2014['temp']<27),'temp1to7_7isMax']=6
ww2014.loc[ww2014['temp'] >=27,'temp1to7_7isMax']=7
ww2014['humid1to5_5isMax']=0
ww2014.loc[ww2014['humid'] < 30,'humid1to5_5isMax']=1
ww2014.loc[(ww2014['humid']>=30)&(ww2014['humid']<41),'humid1to5_5isMax']=2
ww2014.loc[(ww2014['humid']>=41)&(ww2014['humid']<52),'humid1to5_5isMax']=3
ww2014.loc[(ww2014['humid']>=52)&(ww2014['humid']<60),'humid1to5_5isMax']=4
ww2014.loc[ww2014['humid'] >=60,'humid1to5_5isMax']=5
ww2014['wind1to5_5isStrong']=0
ww2014.loc[ww2014['wind'] < 1,'wind1to5_5isStrong']=0
ww2014.loc[(ww2014['wind']>=1)&(ww2014['wind']<3),'wind1to5_5isStrong']=1
ww2014.loc[(ww2014['wind']>=3)&(ww2014['wind']<4),'wind1to5_5isStrong']=2
ww2014.loc[(ww2014['wind']>=4)&(ww2014['wind']<5),'wind1to5_5isStrong']=3
ww2014.loc[ww2014['wind'] >=4,'wind1to5_5isStrong']=4

In [0]:
ww2015['cloud_1234_4isMax']=0
ww2015.loc[ww2015['cloud']<3,'cloud_1234_4isMax']='1'
ww2015.loc[(ww2015['cloud']>=3)&(ww2015['cloud']< 6),'cloud_1234_4isMax']='2'
ww2015.loc[(ww2015['cloud']>=6)&(ww2015['cloud']<=9),'cloud_1234_4isMax']='3'
ww2015.loc[ww2015['cloud']>=9,'cloud_1234_4isMax']='4'
ww2015['temp1to7_7isMax']=0
ww2015.loc[ww2015['temp'] < 4,'temp1to7_7isMax']=1
ww2015.loc[(ww2015['temp']>=4)&(ww2015['temp']<8),'temp1to7_7isMax']=2
ww2015.loc[(ww2015['temp']>=8)&(ww2015['temp']<11),'temp1to7_7isMax']=3
ww2015.loc[(ww2015['temp']>=11)&(ww2015['temp']<16),'temp1to7_7isMax']=4
ww2015.loc[(ww2015['temp']>=16)&(ww2015['temp']<22),'temp1to7_7isMax']=5
ww2015.loc[(ww2015['temp']>=22)&(ww2015['temp']<27),'temp1to7_7isMax']=6
ww2015.loc[ww2015['temp'] >=27,'temp1to7_7isMax']=7
ww2015['humid1to5_5isMax']=0
ww2015.loc[ww2015['humid'] < 30,'humid1to5_5isMax']=1
ww2015.loc[(ww2015['humid']>=30)&(ww2015['humid']<41),'humid1to5_5isMax']=2
ww2015.loc[(ww2015['humid']>=41)&(ww2015['humid']<52),'humid1to5_5isMax']=3
ww2015.loc[(ww2015['humid']>=52)&(ww2015['humid']<60),'humid1to5_5isMax']=4
ww2015.loc[ww2015['humid'] >=60,'humid1to5_5isMax']=5
ww2015['wind1to5_5isStrong']=0
ww2015.loc[ww2015['wind'] < 1,'wind1to5_5isStrong']=0
ww2015.loc[(ww2015['wind']>=1)&(ww2015['wind']<3),'wind1to5_5isStrong']=1
ww2015.loc[(ww2015['wind']>=3)&(ww2015['wind']<4),'wind1to5_5isStrong']=2
ww2015.loc[(ww2015['wind']>=4)&(ww2015['wind']<5),'wind1to5_5isStrong']=3
ww2015.loc[ww2015['wind'] >=4,'wind1to5_5isStrong']=4

In [0]:
ww2016['cloud_1234_4isMax']=0
ww2016.loc[ww2016['cloud']<3,'cloud_1234_4isMax']='1'
ww2016.loc[(ww2016['cloud']>=3)&(ww2016['cloud']< 6),'cloud_1234_4isMax']='2'
ww2016.loc[(ww2016['cloud']>=6)&(ww2016['cloud']<=9),'cloud_1234_4isMax']='3'
ww2016.loc[ww2016['cloud']>=9,'cloud_1234_4isMax']='4'
ww2016['temp1to7_7isMax']=0
ww2016.loc[ww2016['temp'] < 4,'temp1to7_7isMax']=1
ww2016.loc[(ww2016['temp']>=4)&(ww2016['temp']<8),'temp1to7_7isMax']=2
ww2016.loc[(ww2016['temp']>=8)&(ww2016['temp']<11),'temp1to7_7isMax']=3
ww2016.loc[(ww2016['temp']>=11)&(ww2016['temp']<16),'temp1to7_7isMax']=4
ww2016.loc[(ww2016['temp']>=16)&(ww2016['temp']<22),'temp1to7_7isMax']=5
ww2016.loc[(ww2016['temp']>=22)&(ww2016['temp']<27),'temp1to7_7isMax']=6
ww2016.loc[ww2016['temp'] >=27,'temp1to7_7isMax']=7
ww2016['humid1to5_5isMax']=0
ww2016.loc[ww2016['humid'] < 30,'humid1to5_5isMax']=1
ww2016.loc[(ww2016['humid']>=30)&(ww2016['humid']<41),'humid1to5_5isMax']=2
ww2016.loc[(ww2016['humid']>=41)&(ww2016['humid']<52),'humid1to5_5isMax']=3
ww2016.loc[(ww2016['humid']>=52)&(ww2016['humid']<60),'humid1to5_5isMax']=4
ww2016.loc[ww2016['humid'] >=60,'humid1to5_5isMax']=5
ww2016['wind1to5_5isStrong']=0
ww2016.loc[ww2016['wind'] < 1,'wind1to5_5isStrong']=0
ww2016.loc[(ww2016['wind']>=1)&(ww2016['wind']<3),'wind1to5_5isStrong']=1
ww2016.loc[(ww2016['wind']>=3)&(ww2016['wind']<4),'wind1to5_5isStrong']=2
ww2016.loc[(ww2016['wind']>=4)&(ww2016['wind']<5),'wind1to5_5isStrong']=3
ww2016.loc[ww2016['wind'] >=4,'wind1to5_5isStrong']=4

In [0]:
ww2017['cloud_1234_4isMax']=0
ww2017.loc[ww2017['cloud']<3,'cloud_1234_4isMax']='1'
ww2017.loc[(ww2017['cloud']>=3)&(ww2017['cloud']< 6),'cloud_1234_4isMax']='2'
ww2017.loc[(ww2017['cloud']>=6)&(ww2017['cloud']<=9),'cloud_1234_4isMax']='3'
ww2017.loc[ww2017['cloud']>=9,'cloud_1234_4isMax']='4'
ww2017['temp1to7_7isMax']=0
ww2017.loc[ww2017['temp'] < 4,'temp1to7_7isMax']=1
ww2017.loc[(ww2017['temp']>=4)&(ww2017['temp']<8),'temp1to7_7isMax']=2
ww2017.loc[(ww2017['temp']>=8)&(ww2017['temp']<11),'temp1to7_7isMax']=3
ww2017.loc[(ww2017['temp']>=11)&(ww2017['temp']<16),'temp1to7_7isMax']=4
ww2017.loc[(ww2017['temp']>=16)&(ww2017['temp']<22),'temp1to7_7isMax']=5
ww2017.loc[(ww2017['temp']>=22)&(ww2017['temp']<27),'temp1to7_7isMax']=6
ww2017.loc[ww2017['temp'] >=27,'temp1to7_7isMax']=7
ww2017['humid1to5_5isMax']=0
ww2017.loc[ww2017['humid'] < 30,'humid1to5_5isMax']=1
ww2017.loc[(ww2017['humid']>=30)&(ww2017['humid']<41),'humid1to5_5isMax']=2
ww2017.loc[(ww2017['humid']>=41)&(ww2017['humid']<52),'humid1to5_5isMax']=3
ww2017.loc[(ww2017['humid']>=52)&(ww2017['humid']<60),'humid1to5_5isMax']=4
ww2017.loc[ww2017['humid'] >=60,'humid1to5_5isMax']=5
ww2017['wind1to5_5isStrong']=0
ww2017.loc[ww2017['wind'] < 1,'wind1to5_5isStrong']=0
ww2017.loc[(ww2017['wind']>=1)&(ww2017['wind']<3),'wind1to5_5isStrong']=1
ww2017.loc[(ww2017['wind']>=3)&(ww2017['wind']<4),'wind1to5_5isStrong']=2
ww2017.loc[(ww2017['wind']>=4)&(ww2017['wind']<5),'wind1to5_5isStrong']=3
ww2017.loc[ww2017['wind'] >=4,'wind1to5_5isStrong']=4

In [0]:
ww2018['cloud_1234_4isMax']=0
ww2018.loc[ww2018['cloud']<3,'cloud_1234_4isMax']='1'
ww2018.loc[(ww2018['cloud']>=3)&(ww2018['cloud']< 6),'cloud_1234_4isMax']='2'
ww2018.loc[(ww2018['cloud']>=6)&(ww2018['cloud']<=9),'cloud_1234_4isMax']='3'
ww2018.loc[ww2018['cloud']>=9,'cloud_1234_4isMax']='4'
ww2018['temp1to7_7isMax']=0
ww2018.loc[ww2018['temp'] < 4,'temp1to7_7isMax']=1
ww2018.loc[(ww2018['temp']>=4)&(ww2018['temp']<8),'temp1to7_7isMax']=2
ww2018.loc[(ww2018['temp']>=8)&(ww2018['temp']<11),'temp1to7_7isMax']=3
ww2018.loc[(ww2018['temp']>=11)&(ww2018['temp']<16),'temp1to7_7isMax']=4
ww2018.loc[(ww2018['temp']>=16)&(ww2018['temp']<22),'temp1to7_7isMax']=5
ww2018.loc[(ww2018['temp']>=22)&(ww2018['temp']<27),'temp1to7_7isMax']=6
ww2018.loc[ww2018['temp'] >=27,'temp1to7_7isMax']=7
ww2018['humid1to5_5isMax']=0
ww2018.loc[ww2018['humid'] < 30,'humid1to5_5isMax']=1
ww2018.loc[(ww2018['humid']>=30)&(ww2018['humid']<41),'humid1to5_5isMax']=2
ww2018.loc[(ww2018['humid']>=41)&(ww2018['humid']<52),'humid1to5_5isMax']=3
ww2018.loc[(ww2018['humid']>=52)&(ww2018['humid']<60),'humid1to5_5isMax']=4
ww2018.loc[ww2018['humid'] >=60,'humid1to5_5isMax']=5
ww2018['wind1to5_5isStrong']=0
ww2018.loc[ww2018['wind'] < 1,'wind1to5_5isStrong']=0
ww2018.loc[(ww2018['wind']>=1)&(ww2018['wind']<3),'wind1to5_5isStrong']=1
ww2018.loc[(ww2018['wind']>=3)&(ww2018['wind']<4),'wind1to5_5isStrong']=2
ww2018.loc[(ww2018['wind']>=4)&(ww2018['wind']<5),'wind1to5_5isStrong']=3
ww2018.loc[ww2018['wind'] >=4,'wind1to5_5isStrong']=4

In [0]:
ww2019['cloud_1234_4isMax']=0
ww2019.loc[ww2019['cloud']<3,'cloud_1234_4isMax']='1'
ww2019.loc[(ww2019['cloud']>=3)&(ww2019['cloud']< 6),'cloud_1234_4isMax']='2'
ww2019.loc[(ww2019['cloud']>=6)&(ww2019['cloud']<=9),'cloud_1234_4isMax']='3'
ww2019.loc[ww2019['cloud']>=9,'cloud_1234_4isMax']='4'
ww2019['temp1to7_7isMax']=0
ww2019.loc[ww2019['temp'] < 4,'temp1to7_7isMax']=1
ww2019.loc[(ww2019['temp']>=4)&(ww2019['temp']<8),'temp1to7_7isMax']=2
ww2019.loc[(ww2019['temp']>=8)&(ww2019['temp']<11),'temp1to7_7isMax']=3
ww2019.loc[(ww2019['temp']>=11)&(ww2019['temp']<16),'temp1to7_7isMax']=4
ww2019.loc[(ww2019['temp']>=16)&(ww2019['temp']<22),'temp1to7_7isMax']=5
ww2019.loc[(ww2019['temp']>=22)&(ww2019['temp']<27),'temp1to7_7isMax']=6
ww2019.loc[ww2019['temp'] >=27,'temp1to7_7isMax']=7
ww2019['humid1to5_5isMax']=0
ww2019.loc[ww2019['humid'] < 30,'humid1to5_5isMax']=1
ww2019.loc[(ww2019['humid']>=30)&(ww2019['humid']<41),'humid1to5_5isMax']=2
ww2019.loc[(ww2019['humid']>=41)&(ww2019['humid']<52),'humid1to5_5isMax']=3
ww2019.loc[(ww2019['humid']>=52)&(ww2019['humid']<60),'humid1to5_5isMax']=4
ww2019.loc[ww2019['humid'] >=60,'humid1to5_5isMax']=5
ww2019['wind1to5_5isStrong']=0
ww2019.loc[ww2019['wind'] < 1,'wind1to5_5isStrong']=0
ww2019.loc[(ww2019['wind']>=1)&(ww2019['wind']<3),'wind1to5_5isStrong']=1
ww2019.loc[(ww2019['wind']>=3)&(ww2019['wind']<4),'wind1to5_5isStrong']=2
ww2019.loc[(ww2019['wind']>=4)&(ww2019['wind']<5),'wind1to5_5isStrong']=3
ww2019.loc[ww2019['wind'] >=4,'wind1to5_5isStrong']=4

In [0]:
ww2005.to_csv('/content/gdrive/My Drive/data2/ww2005.csv')
ww2006.to_csv('/content/gdrive/My Drive/data2/ww2006.csv')
ww2007.to_csv('/content/gdrive/My Drive/data2/ww2007.csv')
ww2008.to_csv('/content/gdrive/My Drive/data2/ww2008.csv')
ww2009.to_csv('/content/gdrive/My Drive/data2/ww2009.csv')
ww2010.to_csv('/content/gdrive/My Drive/data2/ww2010.csv')
ww2011.to_csv('/content/gdrive/My Drive/data2/ww2011.csv')
ww2012.to_csv('/content/gdrive/My Drive/data2/ww2012.csv')
ww2013.to_csv('/content/gdrive/My Drive/data2/ww2013.csv')
ww2014.to_csv('/content/gdrive/My Drive/data2/ww2014.csv')
ww2015.to_csv('/content/gdrive/My Drive/data2/ww2015.csv')
ww2016.to_csv('/content/gdrive/My Drive/data2/ww2016.csv')
ww2017.to_csv('/content/gdrive/My Drive/data2/ww2017.csv')
ww2018.to_csv('/content/gdrive/My Drive/data2/ww2018.csv')
ww2019.to_csv('/content/gdrive/My Drive/data2/ww2019.csv')